### ISSUE TITLE
Совместимость FCNPC и RouteConnector

### ISSUE THREAD

**Issue by SergGrey** [ziggi/FCNPC#100]
У обоих этих плагинов используются ноды и у обоих есть #define MAX_NODES.
При компелировани естественно вылезет warning 201: redefinition of constant/macro (symbol "MAX_NODES").
Вопрос, как это исправить. И ещё, похожи ли взаимодействия с нодами у этих двух модов? Просто я хочу сделать автобусников не с помощью записи NPC, а с помощью выстраивания пути по нодам. Возможно ли такое провернуть без RouteConnector и если да, то как? Буду благодарен если ткнёте меня лицом в гайд, ибо я про эти ноды ничего путного в интернете не нашёл.

**Comment by WoutProvost** [comment]
Use Google Translate ...
The warning with MAX_NODES will be fixed when #83 gets done.

**Comment by SergGrey** [comment]
Oh thank you.

**Comment by NegativeIQ** [comment]
Poprobuyu nakryakat kak to, prosti za translit.

1. tolko izmeni #define MAX_NODES vo chto to drugoye v odnom iz includov (ya bi zdelal v fcnpc.inc kak v #83 )
2. Vzaimodeystviya to pohozi, no RouteConnector na mnogo lutche.
3. Konecho vozmozhno, obichnimi nodami iz fncpc (to yest iz gta sa), no vopros budet na chto eto budet pohozhe.

No ya tebe skazhu sledusheye, fizika transporta seychas ochyanaya tak chto imey eto v vidu...

**Comment by SergGrey** [comment]
Но это же плагин, разве можно просто так взять и поменять название define'а?

**Comment by NegativeIQ** [comment]
Da, pomenyat nazvaniye define'a mozhno bez problem,, fizicheski eto ne imeyet nichego s plaginom, tolko ne menyay cifri (mozhes postavit menshe, no ne boljshe).

Chtobi ti ponyal. Kogda ti stavis   #define MOY_DEFINE 50
Pawn pre-procesor prosto tupo zamenyayet MOY_DEFINE text na 50 vezde gde on yest v kode.
