### ISSUE TITLE
Error: NPC 'npc10' not created. Another player already connected with that name

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#105]
This is not a real issue but I think the error message is confusing and comes from wrong source... 
When I used GMX to restart my server, during startup I got this error:

> [FCNPC] Error: NPC 'npc10' not created. Another player already connected with that name.
> Failed to create NPC Id npc10(10).

**1- While server was EMPTY.**
2- I don't DESTROY NPCs. (because I NEVER uses GMX)
3- My `OnGameModeExit() ` has nothing inside.
```
public OnGameModeExit()
{
   return 1;
}
```

**Comment by ziggi** [comment]
It is correct. NPCs doesn't disconnects after gmx (like players), but you
are trying to create new NPCs with the names what s already exists on the
server.

**Comment by Yousha** [comment]
Yea but i forgot to say: there isnt any Npc in game
After the gmx

**Comment by ziggi** [comment]
They are connected but not spawned. Anyway, for now all connected NPCs is are despawning after the gmx and FCNPC_Create returns current NPC ID if he is connected.
