### ISSUE TITLE
FCNPC_SetSpeed & FCNPC_GoByMovePath entry/end Point ID

### ISSUE THREAD

**Issue by Naseband** [ziggi/FCNPC#107]
What about adding FCNPC_SetSpeed? For both move paths and regular GoTo movement.
Right now we have to call GoTo/GoByMovePath again to change the speed, but that requires to keep track of the destination and all other arguments.

Changing the speed of an NPC which is going by a move path isn't possible right now since it would start from Point 0 again - we'd have to alter the path to do that.

Which leads me to the following suggestion:

It would be nice to add 2 parameters to FCNPC_GoByMovePath to specifiy an entry and an end point.

So if I have a Move Path that consists of 5 nodes, it would be nice to be able to make one NPC go from Point 1 to Point 3, and another from Point 0 to Point 4 of the same Node Path.

**Comment by ziggi** [comment]
I'm agree about speed suggestion.

Second suggestion is related with: #79

**Comment by ziggi** [comment]
Done.
