### ISSUE TITLE
Nodes are still causing an infinite loop

### ISSUE THREAD

**Issue by karimcambridge** [ziggi/FCNPC#108]
#81

**Comment by ziggi** [comment]
Infinity loop or crash? How much time passes after starts the citizens script and infinity loop (or crash)?

**Comment by karimcambridge** [comment]
Infinite loop AFAIK.

Well I use my own script (edited citizens) .. like 52 npcs. And barely an hour passes.

**Comment by ziggi** [comment]
Please update the plugin to 1.7.6 and check again.

**Comment by karimcambridge** [comment]
Thanks.

You know, maybe it could've been related to https://github.com/ziggi/FCNPC/commit/b72a403d4baf3d796deea7aef5b413a72557f086! Because my NPCs are live, they attack people while they are on their node routes and people can kill them.

I will provide feedback, if it's still happening I'll provide the script.

Also I only found the issue on linux so far (ubuntu 16 and debian 8)

**Comment by ziggi** [comment]
Fixed.
http://forum.sa-mp.com/showpost.php?p=3942104&postcount=3429
