### ISSUE TITLE
Speed NPC in vehicle

### ISSUE THREAD

**Issue by Haze17** [ziggi/FCNPC#110]
Hi

Why if i make:
FCNPC_GoTo(conducteur_avion[0], -406.7596, 2490.1606, 180.2349, FCNPC_MOVE_TYPE_AUTO, FCNPC_MOVE_SPEED_RUN);

The NPC don't "speed" in vehicle ?

Thanks !

**Comment by ziggi** [comment]
Because vehicles can't walk, run or sprint. You should set the value like that:
```Pawn
FCNPC_GoTo(conducteur_avion[0], -406.7596, 2490.1606, 180.2349, FCNPC_MOVE_TYPE_AUTO, 0.5);
```

**Comment by Haze17** [comment]
Hum, the moving with vehicle is low

**Comment by ziggi** [comment]
You can change 0.5 to bigger value.
