### ISSUE TITLE
FCNPC Crashes when NPC dies or when we connect NPCS after starting server.

### ISSUE THREAD

**Issue by Sunehildeep** [ziggi/FCNPC#114]
> =========================== FCNPC Exception Handler ============================
> Address: 0x72ffb1b9
> 
> Registers:
> EAX: 0x0 - EBX: 0x18fc34 - ECX: 0x1e79fd88 - EDX: 0x1
> ESI: 0x2163ef68 - EDI: 0x4a - EBP: 0x18fc20 - ESP: 0x18fb4c
> 
> Stack:
> 0x0: 0x1e79fd88 - 0x4: 0x1e79fd88 - 0x8: 0x534c6f76 - 0xC: 0x231abb78 - 0x10: 0x1e79fd88 - 0x14: 0x0
> 0x18: 0x72ca37e0 - 0x1C: 0x73021cf0 - 0x20: 0x0
> 
> Information:
>   System: Windows
>   SA-MP: 0.3.7 R2
>   FCNPC: 1.7.6
> 
> Functions:
>   FUNC_CPlayerPool__DeletePlayer: 0x466570
>   FUNC_CPlayer__Kill: 0x484620
>   FUNC_CPlayer__EnterVehicle: 0x484c70
>   FUNC_CPlayer__ExitVehicle: 0x484f50
>   FUNC_CPlayer__SpawnForWorld: 0x486d30
>   FUNC_GetVehicleModelInfo: 0x488240
>   FUNC_CConsole__GetIntVariable: 0x48b5b0
>   FUNC_ClientJoin_RPC: 0x4918f0
> 
> Pointers:
>   VAR_ServerAuthentication: 0x4f5fe8
>   VAR_NetVersion: 0xfd9
> 
> Offsets:
>   OFFSET_RemoteSystemManager: 0x33c
>   OFFSET_RemoteSystemSize: 0xcb8
>   OFFSET_RemoteSystem__ConnectMode: 0xcb0
>   OFFSET_RemoteSystem__Unknown: 0xcb5
> =========================== FCNPC Exception Handler ============================
> 

This is the same error while both the situations, even me and ToiletDuck reported it on the thread, but no one looked onto it, so I came here to report it.
My include orders are :-

```
// Includes
#include <a_samp>		// SAMP Team
#include <YSI\y_utils>
#define ENABLE_3D_TRYG_YSI_SUPPORT
#include <crashdetect>
#include <audio>
#include <YSI\y_timers>
#include <a_mysql>   	//
#include <easyDialog>   	// Emmet_
#include <sscanf2>
#include <izcmd>        	// Yashas
#include <timestamptodate>  // Jochemd
#include <streamer>         // Incognito
#include <ColAndreas>
#include <FCNPC>
#include <3DTryg>

new MySQL:mysql;
// Other includes
#include <inv>
#include "./zombie2.pwn" // In here, the zombie's connect.
#include <Trees>

```

My loading function from zombie2.pwn
```
new timer;

public OnGameModeInit()
{
timer = SetTimer("LoadZombies",10,true);
return 1;
}

public LoadZombies()
{
    new name[24], then_npc;
    format(name, sizeof(name), ZOMBIE_NAME, zombie_count + 1);
    then_npc = FCNPC_Create(name);
    ZombieTimer[then_npc] = repeat ZombieRoam(then_npc);
    SetZombieSpawnConfig(then_npc);
    zombie_count++;
    if(zombie_count == MAX_ZOMBIES)
		KillTimer(timer);
    return 1;
}
```
I've tried commeting SetZombieSPawnConfig, ZombieTimer[then_npc] to debug out, still the same crash.
No matter at how many MS the timer of LoadZombies is set to, it does crash.

**Comment by ziggi** [comment]
Problem was in AMX stack due to Pawn recursion.
Fixed.
