### ISSUE TITLE
Possible conflict - OnFilterScriptExit

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#117]
I'm not sure it's about **FCNPC** plugin or **MapFix** library but found this:

D:\FCNPC.inc(423) : error 021: symbol already defined: "SSCANF_OnFilterScriptInit"
D:\dynamicgz.inc(447) : error 021: symbol already defined: "OnFilterScriptExit"

MapFix library: http://forum.sa-mp.com/showthread.php?p=3962807
**MapFix's OnFilterScriptExit:**
```
public OnFilterScriptExit()
{
	if(MapFixIsEnabled < 2)
	{
		printf("  MapFix by Nexius v%s unloaded (filterscript version).", MAPFIX_VERSION);
		DestroyMapFixObjects();
		#if defined DeleteSVar
			DeleteSVar("MapFixIsEnabled");
		#endif
	}
	return 1;
}
```

FCNPC include version: 1.7.4
MapFix library version: 3.2.1

**Comment by ziggi** [comment]
Try to use include version of MapFix.

**Comment by Yousha** [comment]
Thanks, solved.
NOT a bug.
