### ISSUE TITLE
Баг перемещения бота посредством передвижения объекта :)

### ISSUE THREAD

**Issue by ukenjutsu** [ziggi/FCNPC#118]
Доброго времени суток.
Чем писать кучу текста, проще показать все на видео :) (не знал куда залить, поэтому пришлось запаковать в zip 👍)

[2017.12.13-20.31.zip](https://github.com/ziggi/FCNPC/files/1556433/2017.12.13-20.31.zip)

Во время экспериментов над FCNPC, я узнал, что все боты обновляются через определенное кол-во миллисекунд и поэтому возвращаются на свои изначальные позиции. Вскоре обнаружил функцию FCNPC_SetUpdateRate, которая насколько я понял позволяет установить свой интервал обновления. Я изменил его на 5000 и боты перестали падать сквозь объекты на целых несколько секунд! (несколько секунд Карл! xD). Но как только интервал в 5 секунд проходил, они вновь возвращались на свои изначальные позиции.

Ставить интервал в 99999999 не вариант, поскольку от этого зависит стрельба ботов, их передвижение и т.д (я так думаю).

P.s. 
Пробовал создавать объекты без стримера.
Пробовал различные модели объектов (всякие камни, ящики и т.д).
Пробовал использовать функцию FCNPC_SetSurfingObject, но почему-то боты исчезали вовсе.
Пробовал подключать MapAndreas.
Пробовал устанавливать анимацию ботам.
Пробовал использовать функцию FCNPC_SetMinHeightPosCall (без понятия для чего она... вроде бы устанавливает какую-то минимальную высоту).
Пробовал создавать ботов и объекты в основном виртуальном мире (это уже от отчаяния xD).

**Comment by ziggi** [comment]
Через FCNPC_SetSurfingObject должно сработать. Чтобы подкорректировать положение, используй FCNPC_SetSurfingOffsets. Ещё можно попробовать возвращать 0 в FCNPC_OnUpdate, но лучше первый вариант.

**Comment by NegativeIQ** [comment]
FCNPC_SetSurfingOffsets prinimayet/ozhidayet samp object bez streamera, tak chto imey eto v vidu.

**Comment by ukenjutsu** [comment]
Спасибо :)
Заработало когда я вызвал функцию FCNPC_SetSurfingObject после функции MoveObject.
Вопрос, нужно ли вызывать данную функцию каждый раз после вызова функции MoveObject?

Можно поподробнее о функции FCNPC_SetSurfingOffsets? Просто у меня и без нее все работает.

**Comment by ziggi** [comment]
> Вопрос, нужно ли вызывать данную функцию каждый раз после вызова функции MoveObject?

Нет.

> Можно поподробнее о функции FCNPC_SetSurfingOffsets? Просто у меня и без нее все работает.

Это координаты смещения относительно объекта, используй, если хочешь немного передвинуть бота.

**Comment by WoutProvost** [comment]
Google translate works quite well, but you don't see me talking in my native language. If you would use English instead, more people would be able to help you or see that they have the same problem and join the conversation.

**Comment by ukenjutsu** [comment]
У меня в OnPlayerConnect такой порядок вызова функций:
CreatePlayerObject - создаю 5 объектов для ботов
FCNPC_SetInvulnerable 
FCNPC_Spawn
FCNPC_SetHealth
FCNPC_SetAngle
FCNPC_SetVirtualWorld
FCNPC_SetSurfingPlayerObject - задаю нужный объект

Но плагин FCNPC крашит....
А если FCNPC_SetSurfingPlayerObject вызывать после MovePlayerObject и еще указать смещение через FCNPC_SetSurfingOffsets, то все работает (если не указать смещение, то боты просто исчезают как только объект начинает двигаться).

**Comment by ziggi** [comment]
CreatePlayerObject создаёт объект, видимый только переданному playerid, а на твоём видео ты видишь эти объекты, что означает, что ты передаёшь id объекта, созданного для игрока, боту, что и вызывает краш. Нужно использовать CreateObject и FCNPC_SetSurfingObject.

**Comment by NegativeIQ** [comment]
@ziggi baga net, da i pomoch bolshe nechem vsyo chotko skazano, dumayu mozhno zakrit temu.
