### ISSUE TITLE
Add ability to show/hide NPCs nameplates

### ISSUE THREAD

**Issue by ziggi** [ziggi/FCNPC#119]
Visible NPC HP Bar: http://forum.sa-mp.com/showthread.php?t=632664
Code: https://raw.githubusercontent.com/AbyssMorgan/SA-MP/master/include/SAM/vnpc.inc
Related functions: https://github.com/kurta999/YSF/blob/b27a575300f101cdacb9326582348c90d92eb0ef/src/natives/players.cpp#L696-L740

**Comment by karimcambridge** [comment]
Pls don't let this go down the path of CNPC.

Find out if this won't cause any drama first.

**Comment by ziggi** [comment]
This is not like CNPC. This solution affects only for specific players, not on server playerd

**Comment by NegativeIQ** [comment]
These is interesting...i dont like memory hacking but then again raknet structure on server side didnt change for a long time and memory address is exported in a variable...

Anyway these woul require us to hook onto raknet and in perspective it could mean per player NPC's streaming...
