### ISSUE TITLE
Crash due to no isnull check with strcmp

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#121]
I was testing #89 when I encountered this bug. When giving an empty name with FCNPC_Create, the server crashes instead of displaying the error. The crash is probably cause [here](../../FCNPC/blob/master/src/CPlayerManager.cpp#L151).

Other strcmp uses:
* CAnimationInfo.cpp: [line 394](../../FCNPC/blob/master/src/CAnimationInfo.cpp#L394)
* CServer.cpp: [line 189](../../FCNPC/blob/master/src/CServer.cpp#L189)
* CRecordManager.cpp: [line 105](../../FCNPC/blob/master/src/CRecordManager.cpp#L105)
* CHooks.cpp: [line 97](../../FCNPC/blob/master/src/CHooks.cpp#L97)
* FCNPC.inc.in: [line 498](../../FCNPC/blob/master/src/FCNPC.inc.in#L498)

Not all of them have user input or are part of the .dll, but I think the point is clear, you decide where to add the isnull check.
```Pawn
#define isnull(%1) ((%1[0] == 0) || (%1[0] == 1 && %1[1] == 0))
```
I think isnull is preferred over strlen == 0, since we're mostly dealing with user input.

**Comment by ziggi** [comment]
The problem was in `IsValidNickName` function: `strlen` causes an error if it get null pointer.
