### ISSUE TITLE
Client stops receiving updates

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#122]
Regarding [this post](http://forum.sa-mp.com/showpost.php?p=3976578&postcount=3486) and [my reply](http://forum.sa-mp.com/showpost.php?p=3976595&postcount=3487).

There seems to be something happening that makes the client stop receiving updates.

In **jop9888** case it happens with FCNPC_AimAt. In my case it happens with PutPlayerInVehicle and somewhere else that's difficult to describe (when the NPC's position is set too close to a certain vehicle).

I will try to isolate the bug in a small filterscript and if needed make a video to demonstrate the weird behaviour.

**Comment by ziggi** [comment]
Try to use this version of FCNPC: [FCNPC-nopingfix.zip](https://github.com/ziggi/FCNPC/files/1609840/FCNPC-nopingfix.zip)

**Comment by WoutProvost** [comment]
Nope that doesn't fix it.

I've had this bug for a long time, so it's not a recent update. On 21/sep/2017 I first logged the bug, but it could have existed before that date.

**Comment by WoutProvost** [comment]
I'll investigate if it has something to do with [this](http://forum.sa-mp.com/showthread.php?t=640644) or [this](http://forum.sa-mp.com/showthread.php?t=642085) update, since that seems to be around the time I logged the bug.

**Comment by WoutProvost** [comment]
I think I found it. The cause is certainly not the SA-MP client or server updates, but definitely FCNPC.

When I roll back my repo to the exact commit before I updated to FCNPC 1.7.4, the bug is not present. 
When I roll back my repo to when I updated to FCNPC 1.7.4, the bug occurs.

**FCNPC 1.7.4**, that's where we have to investigate.

**Comment by jop9888** [comment]
It did fix the bug i was facing since v1.8.0, thank you both for your help

**Comment by WoutProvost** [comment]
Yep, just tested.
