### ISSUE TITLE
[FCNPC] Error: NPC 'Test' not created.

### ISSUE THREAD

**Issue by memurt** [ziggi/FCNPC#123]
I'm getting this error. Can you update plugin for 0.3.8-RC4-1?

**Comment by ziggi** [comment]
No, 0.3.8 was canceled. 0.3.7-DL support possible, but i'm not sure.

**Comment by NegativeIQ** [comment]
Well 0.3.7-DL should be supported, and i actually expect it to be more used then 0.3.7. But that/this conversation is for when 0.3.7-DL is released (and not RC version)
