### ISSUE TITLE
SA-MP DL Version

### ISSUE THREAD

**Issue by NegativeIQ** [ziggi/FCNPC#125]
First of all, i think DL should not have separate repository. While its easy to apply changes from master repository using git, i would go with optional compiler flag that would switch 0.3.7 and DL versions. Keep two structure and hook (two samp versions) files and include one or another depending if compiler flag has been provided (if its defined). Dont know why but i think its way easier to maintain plugin like that. But these is totally up you and not for discussion since you do everything about plugin.

Second thing, is small TODO list.

- [x] Implement function to check if object model is valid and add/remove 0.3.7-DL ranges

- [x] Implement function to check if skin model is valid and add/remove 0.3.7-DL ranges

- [x] GetPlayerSkin and GetPlayerCustomSkin fcnpc wrappers

- [x] Check all functions depending on samp timers in 0.3.7-DL 

- [x] MAX_OBJECTS has been increased to 2000 in 0.3.7-DL (does these affect plugin? - Think structure offsets)

**Comment by ziggi** [comment]
> Implement function to check if object model is valid and add/remove 0.3.7-DL ranges

FCNPC doesn't checks object models, so this is no needed.

> Implement function to check if skin model is valid and add/remove 0.3.7-DL ranges

Partly ready, but we need to hook CArtInfo structure for this.

> GetPlayerSkin and GetPlayerCustomSkin fcnpc wrappers

Done.

> Check all functions depending on samp timers in 0.3.7-DL

What is "samp timers in 0.3.7-DL", I don't understand.

**Comment by NegativeIQ** [comment]
> Limits the game timer some more to fix camera interpolation bugs, although increases the risk of a timer wrap.

[Source](http://forum.sa-mp.com/showthread.php?t=644105)

In 0.3.8-RC4-3 Kalcor introduced/changed something with game timers, and knowing how timers are implemented on server its possible they are affected. If FCNPC does not use or rely onto SetTimer(Ex) and MoveObject functions then everything should be fine.

**Comment by Bruno13** [comment]
In 0.3.7-DL version I'm getting the error "[FCNPC] Error: NPC 'npc' not created. Name 'npc' is invalid or the maxnpc limit in server.cfg has been reached" but maxnpc is correct and the nane too.

Please fix it.

**Comment by ziggi** [comment]
Completed in 2b49ed35f9ebb3ce0b94733d0f1ba5328e10e7a8 and 55bdb951977568ad37d1f822868a0637f562c0bf

**Comment by edgarpochtel** [comment]
Nice work. Will be there a release version or need I to complie it on my own?

**Comment by ziggi** [comment]
@edgarpochtel 2.0 is not ready yet, so, you have to compile it by yourself.
