### ISSUE TITLE
SAMP server can not load FCNPC for some unknown reason

### ISSUE THREAD

**Issue by AmyrAhmady** [ziggi/FCNPC#129]
Hi ! I get this error while loading FCNPC.dll : 
I've installed MS VR C++ 2015 and older versions but not fixed!

```
---------------------------
samp-server.exe - Entry Point Not Found
---------------------------
The procedure entry point K32GetModuleInformation could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```
My server host OS is Windows Server 2008

**Comment by ziggi** [comment]
It's loads without FCNPC (show logs)? Is `main() {}` exists in your code?

**Comment by AmyrAhmady** [comment]
samp server won't crash just FCNPC get failed in loading..
and yes main() exist however it isn't related to script because it happens before loading gamemode , just a windows error like this : 

http://i62.tinypic.com/k4xftv.jpg

**Comment by ziggi** [comment]
Try to install VC++ Redistributable 2017 too.

**Comment by AmyrAhmady** [comment]
Tried right now , still the same...

**Comment by ziggi** [comment]
Can you try to install all updates for your server OS?

**Comment by AmyrAhmady** [comment]
Nope , my server hosting provider doesn't let me to update , it is disabled by default

**Comment by AmyrAhmady** [comment]
I even used FCNPC v1.0.0 , it doesn't work neigther

**Comment by 0x416c69** [comment]
Maybe it's in Psapi.dll ?
Try that dll I sent to you.

**Comment by NegativeIQ** [comment]
Can you please specify OS, Build and architecture?

**Comment by ziggi** [comment]
Out of date
