### ISSUE TITLE
Equivalent GetPlayerTargetPlayer

### ISSUE THREAD

**Issue by JoaquinZc** [ziggi/FCNPC#134]
Me gustaría que fuera posible hacer un evalente de GetPlayerTargetPlayer para FCNPC. He intentado hacerlo con las funciones nativas de samp, pero no lo logro. Lo estoy usando porque quiero saber si no hay un objeto obstrullendo el disparo y no quiero usar ColAndreas.

**Comment by ziggi** [comment]
Not possible without ColAndreas.
