### ISSUE TITLE
Custom NPC Skin

### ISSUE THREAD

**Issue by MaxAndolini** [ziggi/FCNPC#135]
[FCNPC] Error: NPC 'Bad Dog' not created. Name 'Bad Dog' is invalid or the maxnpc limit in server.cfg has been reached.

maxnpc 100

**Comment by WoutProvost** [comment]
Already known:
http://forum.sa-mp.com/showpost.php?p=3997724&postcount=3529
#125

**Comment by ziggi** [comment]
Space isn't allowed in nick names.
