### ISSUE TITLE
MovePath crash

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#143]
The server crashes when using multiple movepaths. Caused by commit c337580. Maybe related to #124.

While performing the movepath my NPCs can be stopped with `FCNPC_Stop` or can start moving somewhere else with `FCNPC_GoTo(Player)`. Maybe that has something to do with it, not sure.

I'm trying to isolate and reproduce the problem, but I haven't succeeded yet.

**Comment by WoutProvost** [comment]
Found the actual cause:
The crash doesn't happen when I use `FCNPC_INVALID_MOVEPATH_ID`.

**Comment by ziggi** [comment]
Seems to be fixed

**Comment by ziggi** [comment]
Fixed.
