### ISSUE TITLE
Unable to work on samp version 0.37

### ISSUE THREAD

**Issue by Xing-C** [ziggi/FCNPC#153]
Unable to work on samp version 0.37, the server's previous version is 0.3z.
Error message;

Script[gamemodes/SAMP.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0

**Comment by Xing-C** [comment]
I'm sure samp.amx exists because he's normal in the 0.3z version.

**Comment by ziggi** [comment]
What version of FCNPC you are using?

**Comment by Dayvison** [comment]
You can use crashdetect to see the missing functions, it may not be related to fcnpc

**Comment by Xing-C** [comment]
The version I used before is 1.0
Current version 1.2.1

**Comment by Xing-C** [comment]
@ziggi

**Comment by ziggi** [comment]
So, you should upgrade your plugin to latest (1.8.2) update the include and fix your scripts.
