### ISSUE TITLE
FCNPC_RECORD

### ISSUE THREAD

**Issue by MakeMyName** [ziggi/FCNPC#158]
In the early version there was such a function as
**native FCNPC_StartRecordingPlayback (npcid, file []);**
Can you add it to version 2.0 ?

**Comment by ziggi** [comment]
It's renamed to `FCNPC_StartPlayingPlayback`

**Comment by ziggi** [comment]
What this function should do?

**Comment by MakeMyName** [comment]
Yes, now it was renamed **FCNPC_StartPlayingPlayback**
But it only reproduces an already prepared record,  this function would write it in server

**Comment by WoutProvost** [comment]
> this function would **write** it in server

By **write** do you mean that the server should start gathering NPC data in a .rec file like [StartRecordingPlayerData](http://wiki.sa-mp.com/wiki/StartRecordingPlayerData) does with player data?

**Comment by MakeMyName** [comment]
exactly

**Comment by WoutProvost** [comment]
Have you tried using **StartRecordingPlayerData** on the NPC, or does that not work?

But I really don't see why you would even want that, because:
1. recording the data yourself will give much more accurate data than when you would record NPC data
2. repeated actions (e.g. movement) can always be executed with the current FCNPC movement functions

So, can you explain a bit further what your use case is exactly?

**Comment by MakeMyName** [comment]
**StartRecordingPlayer** has the types of records, so I can only write **npc onfoot** or **npc driver**

But FCNPC can enter and exit the transport, I just want to make npc which can be onfoot and driver at the same time, without a record break , is this even possible do with FCNPC ?

**Comment by MakeMyName** [comment]
Yes, it works but it's not exactly what I'm expected

> 2. repeated actions (e.g. movement) can always be executed with the current FCNPC movement functions

Well, if for example I record a bot that just shoots, it will not be able to fire at the Z coordinate, it will not have any shoots effects. 
But if I just create a bot with function **FCNPC_AimAtPlayer**, it will shoot at the Z coordinate and the effects of shoots will be visible

**Comment by ziggi** [comment]
For me it seems like a strange suggestion, I'm not really understand the point of this suggestion. If you want, you can try to explain this a little bit simpler.
