### ISSUE TITLE
FCNPC_LoadPlayingPlayback file handle is not closed

### ISSUE THREAD

**Issue by Naseband** [ziggi/FCNPC#170]
https://github.com/ziggi/FCNPC/blob/4adc8a6fed6d5e0005800eb04fcefea05b18785c/src/CRecordManager.cpp#L83

Since the file is already stored in memory, shouldn't the file be closed at the end of the function? No reference to it is stored elsewhere so I assume it should be closed.

This is a problem I just experienced with a Race Ghost NPC. I can't replace the recording when a player did a better round time, only after closing the server.

**Comment by ziggi** [comment]
It seems you are right.
