### ISSUE TITLE
 FCNPC_SetSkin and FCNPC_Spawn Problems [0.3.DL] [2.0 RC7]

### ISSUE THREAD

**Issue by recepilhanli** [ziggi/FCNPC#180]
If you use FCNPC_SetSkin and FCNPC_Spawn functions server will crash.

=========================== FCNPC Exception Handler ============================
Address: 0x6ebadf69

Registers:
EAX: 0x0 - EBX: 0x2857078 - ECX: 0x8c58e00 - EDX: 0x6eb96712
ESI: 0x7a - EDI: 0x8c58e00 - EBP: 0x19fa1c - ESP: 0x19fa18

Stack:
0x0: 0x7a - 0x4: 0x19fb5c - 0x8: 0x6ebbd278 - 0xC: 0x7a - 0x10: 0xf668c84b - 0x14: 0x7a
0x18: 0x8c58e00 - 0x1C: 0x2857078 - 0x20: 0x9

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================

**Comment by ziggi** [comment]
Fixed https://github.com/ziggi/FCNPC/releases/tag/v2.0.9
