### ISSUE TITLE
Invalid names if you don't use "_"

### ISSUE THREAD

**Issue by Malganys** [ziggi/FCNPC#187]
Hello, as the title says there is a bug (or I don't know if it's something related with security) with FCNPC_Create, which is that if you don't add "_" to string name, the server drops an error. i.e: 

`FCNPC_Create("Kiko"); // This drops an error`
`FCNPC_Create("Kiko_"); // but this no`

Sorry if my english is bad.

**Comment by ziggi** [comment]
What kind of error? Did you try on empty server script?

**Comment by Malganys** [comment]
> What kind of error? Did you try on empty server script?

I tried on an empty script, the error is: 
`[FCNPC] Error: NPC 'kiko' not created. Name 'kiko' is invalid or the maxnpc limit in server.cfg has been reached.`
