### ISSUE TITLE
Filterscripts examples

### ISSUE THREAD

**Issue by Tyrar** [ziggi/FCNPC#19]
Hi there,

I decided to include the plugin on my project. At the beggining, I tested *bg.pwn* (FS) but NPC bots didn't follow me (I used the command */bg*).

Futhermore, I tried the shooting function, but it didn't work correctly.
- /bg shoot *bot_id* *player_id* => here, the bot juste aim at me
- /bg reset *bot_id* => the bot started to shoot at me...

I tested with a blanck gamemode, it was the same problem.

----
I tried it on :
- W10 64bits
- Debian 8.5 64bits
- SAMP version : 0.3.7 R2

**Comment by ziggi** [comment]
Ohh, this script seems completely outdated, I will rewrite it.

**Comment by Tyrar** [comment]
Hum ok :p 
I will try by myself, thank you for the answer !
