### ISSUE TITLE
Поворот npc

### ISSUE THREAD

**Issue by AntonP911** [ziggi/FCNPC#20]
Привет.
Как мне повернуть бота на 10 градусов в лево\право, относительно его направления?
Так пытался
```
stock AI_MotionTurn(npcid, Float:incangle)
{
	new Float:fangle = FCNPC_GetAngle(npcid);
	FCNPC_Stop(npcid);
	FCNPC_SetAngle(npcid, fangle - incangle);
 	return 1;
}
```

И так
```
stock AI_MotionTurn(npcid, Float:incangle)
{
	new Float:fangle;
	GetPlayerFacingAngle(npcid, fangle);
	FCNPC_Stop(npcid);
	SetPlayerFacingAngle(npcid, fangle - incangle);
 	return 1;
}
```

А вызывал сток соответственно так `AI_MotionTurn(npcid, 10.0);`
Но какое бы значение я не ставил он поворачивается на более чем 90 градусов.
Может я что-то не догоняю?:(
Даже когда я ставлю просто  FCNPC_SetAngle(npcid, incangle); Всеравно поворачивается на более чем нужно.

**Comment by Crayder** [comment]
Translation: His NPC's are rotating more than he wants.

**Comment by ziggi** [comment]
Проверил, такой проблемы нет, используй первый вариант функции.
Возможно ты используешь не последнюю версию плагина.
