### ISSUE TITLE
Expression: vector iterator not incrementable, Standard C++ Libraries Out of Range && O

### ISSUE THREAD

**Issue by rufcio** [ziggi/FCNPC#204]
after the latest windows update, which I have delayed 2 months (intuition -.---) it happened:
![fcnpc1](https://user-images.githubusercontent.com/31253495/67266256-11b4e500-f4b0-11e9-8435-a5e74495e7ba.png)
![fcnpc2](https://user-images.githubusercontent.com/31253495/67266257-11b4e500-f4b0-11e9-9fbb-14ffebd967ac.png)

Version: FCNPC 2.0.0 RC7 0.3-DL (Without Pathfinding Feature)

**Comment by MacLove13** [comment]
UP!

**Comment by MacLove13** [comment]
Someone?
