### ISSUE TITLE
Server crashing on command.

### ISSUE THREAD

**Issue by ratasky** [ziggi/FCNPC#213]
I am using Latest release, 1.8.2
=========================== FCNPC Exception Handler ============================
Address: 0x75674dbd

Registers:
EAX: 0x18f578 - EBX: 0x18f62c - ECX: 0x3 - EDX: 0x0
ESI: 0x73f81444 - EDI: 0x74066630 - EBP: 0x18f5d0 - ESP: 0x18f578

Stack:
0x0: 0xe06d7363 - 0x4: 0x1 - 0x8: 0x0 - 0xC: 0x75674dbd - 0x10: 0x3 - 0x14: 0x19930520
0x18: 0x18f62c - 0x1C: 0x74066630 - 0x20: 0x4e38ce8

Information:
  System: Windows
  SA-MP: Unknown
  FCNPC: 1.8.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485672
  FUNC_CPlayer__ExitVehicle: 0x485952
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5
=========================== FCNPC Exception Handler ============================

**Comment by ziggi** [comment]
You are using unsupported version of SA-MP server.

**Comment by LukastheDev** [comment]
Using 0.3 DL R1, what is recommended version for that?

**Comment by LukastheDev** [comment]
On the server, when i use a certain command, server crashing and creating fcnpc crash file.

**Comment by ziggi** [comment]
Only 2.0 branch supports DL version.
