### ISSUE TITLE
Filterscripts examples

### ISSUE THREAD

**Issue by Tyrar** [ziggi/FCNPC#22]
Hello,

Is the citiziens filterscript outdated ? I tried it and all the citiziens are on the sea.

Thanks,

Tyrar

**Comment by ziggi** [comment]
It's possible, I will rewrite this script soon.

**Comment by Crayder** [comment]
I don't think it is though, that's the script I used to test FCNPC not too long ago (about 2 months)... :/

**Comment by Tyrar** [comment]
For the test, I tried on my gamemode and a blanck gamemode.

I added the node information in the filescripts directory. Unfortunatelly, all bots are on the sea and don't appear on the map.

**Comment by Crayder** [comment]
I'll test it later so ZiGGi can know for sure, I might even make a new one if it is indeed messed up.

**Comment by ziggi** [comment]
Fixed in 4425dbf24df32675bd164a7885ab993af906561b
