### ISSUE TITLE
Use "version" subfield in pawn.json for sampctl v1.9.0

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#221]
See [this](https://github.com/Southclaws/sampctl/issues/311) issue and [this](https://github.com/Southclaws/sampctl/wiki/Plugin-Packages) wiki page.

When sampctl `v1.9.0` is released, we don't need the confusing `v2.0.0-rc.7` and `v2.0.0-rc.7-03DL` releases anymore, but both binaries can be bundled up into one single `v2.0.0-rc.7` release.

**Comment by ziggi** [comment]
#260
