### ISSUE TITLE
Suggestion: Function to show or hide NPC health bar per player

### ISSUE THREAD

**Issue by Awide** [ziggi/FCNPC#248]
It would be nice to have a function that shows or hides the NPC's health/armour bars per player.

**Comment by ziggi** [comment]
Try this: https://team.sa-mp.com/wiki/ShowPlayerNameTagForPlayer.html

**Comment by Awide** [comment]
Thanks for the tip, I tried! It did not do anything. _FCNPC_ShowInTabListForPlayer_ works though, but then they are shown in the tablist.

**Comment by ziggi** [comment]
Oh, it's a sa-mp feature. You cannot show the name of the NPC. Tablist function is everything what you can get. Also you can use 3D text to display the name of the NPC.
