### ISSUE TITLE
Crash after NPC Join 2.0.3 (Debian 10)

### ISSUE THREAD

**Issue by Abyss-z94** [ziggi/FCNPC#255]
My server got crashes when NPC join server, what should i do to fix it?

[14/09/2021 02:32:28] Tried to reload Map.
[14/09/2021 02:32:28] [npc:join] taxi_0 has joined the server (499:127.0.0.1)

=========================== FCNPC Exception Handler ============================
Signal 11 (Segmentation fault), address is 2ef from f7f4d96a

Backtrace:
  #0 in plugins/FCNPC-DL.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x126) [0xf6262876]
  #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf7f59090]
  #2 in plugins/sscanf.so(+0xb96a) [0xf7f4d96a]
  #3 in ./samp03svr() [0x809d844]
  #4 in ./samp03svr() [0x809f2e5]
  #5 in plugins/profiler.so(amx_Exec+0x31) [0xf7a74da1]
  #6 in plugins/profiler.so(_ZN15ProfilerHandler4ExecEPii+0x4f) [0xf7a774ff]
  #7 in plugins/profiler.so(+0x1211b) [0xf7a7611b]
  #8 in plugins/streamer.so(+0x2d932) [0xf79b3932]
  #9 in [0x2e7]

Information:
  System: GNU/Linux
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.3

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x80dc0b0
  FUNC_CPlayer__Kill: 0x80d5ac0
  FUNC_CPlayer__EnterVehicle: 0x80d6a70
  FUNC_CPlayer__ExitVehicle: 0x80d6bf0
  FUNC_CPlayer__SpawnForWorld: 0x80d7870
  FUNC_GetVehicleModelInfo: 0x80e14f0
  FUNC_CConsole__GetIntVariable: 0x80a87d0
  FUNC_ClientJoin_RPC: 0x80ba350

Pointers:
  VAR_ServerAuthentication: 0x81b7d2c
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x334
  OFFSET_RemoteSystemSize: 0xc69
  OFFSET_RemoteSystem__ConnectMode: 0xc62
  OFFSET_RemoteSystem__Unknown: 0xc67
=========================== FCNPC Exception Handler ============================

**Comment by ziggi** [comment]
Look at backtrace, the problem is in sscanf.

**Comment by Abyss-z94** [comment]
> Look at backtrace, the problem is in sscanf.

Ah i got it, im just solved that with set a timer to connect FCNPC, thank for reply!
