### ISSUE TITLE
Disable damage possible?

### ISSUE THREAD

**Issue by Awide** [ziggi/FCNPC#256]
Is it possible to disable/prevent damage done by FCNPC? Setting the player and the NPC into the same team does not seem to work. I want to use custom damage values with a custom "fake" death system.

**Comment by ziggi** [comment]
Where you set the team for the NPC? I think it should work. Also you can `return 0` in `OnWeaponShot` to prevent sending bullet.

**Comment by Awide** [comment]
> Where you set the team for the NPC? I think it should work. Also you can `return 0` in `OnWeaponShot` to prevent sending bullet.

The team didn't work, but returning 0 in OnWeaponShot did! Thank you ziggi!

**Comment by ziggi** [comment]
Try to set the team in `FCNPC_OnCreate`.
