### ISSUE TITLE
sampctl error

### ISSUE THREAD

**Issue by kolor4do** [ziggi/FCNPC#262]
```
PS C:\IAS> sampctl p build
ERROR: Dependency include path errors found:
ERROR: Duplicate 'colandreas.inc' found in both
'C:\IAS\dependencies\ColAndreas\Server\include'
'C:\IAS\dependencies\FCNPC\sampsvr_files'

could not compile due to conflicting filenames located in different include paths
```

**Comment by ADRFranklin** [comment]
Well of course this is going to happen, if you include ColAndreas as a separate package, while FCNPC comes with ColAndreas also.

The solution would be to use the ColAndreas that comes with FCNPC and not include ColAndreas separately.
