### ISSUE TITLE
how install??

### ISSUE THREAD

**Issue by TukangM** [ziggi/FCNPC#270]
----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team

Server Plugins
--------------
 Loaded 0 plugins.

Started server on port: 7777, with maxplayers: 50 lanmode is OFF.

Filterscripts
---------------
  Loading filterscript 'bodyguards.amx'...
  Unable to load filterscript 'bodyguards.amx'.
  Loading filterscript 'citizens.amx'...
  Unable to load filterscript 'citizens.amx'.
  Loading filterscript 'missions.amx'...
  Unable to load filterscript 'missions.amx'.
  Loading filterscript 'sample.amx'...
  Unable to load filterscript 'sample.amx'.
  Loading filterscript 'traindrivers_pilots.amx'...
  Unable to load filterscript 'traindrivers_pilots.amx'.
  Loaded 0 filterscripts.

Loaded 3 vehicles from: vehicles/trains.txt
Loaded 3 vehicles from: vehicles/pilots.txt
Loaded 15 vehicles from: vehicles/lv_law.txt
Loaded 39 vehicles from: vehicles/lv_airport.txt
Loaded 255 vehicles from: vehicles/lv_gen.txt
Loaded 38 vehicles from: vehicles/sf_law.txt
Loaded 35 vehicles from: vehicles/sf_airport.txt
Loaded 353 vehicles from: vehicles/sf_gen.txt
Loaded 24 vehicles from: vehicles/ls_law.txt
Loaded 37 vehicles from: vehicles/ls_airport.txt
Loaded 98 vehicles from: vehicles/ls_gen_inner.txt
Loaded 389 vehicles from: vehicles/ls_gen_outer.txt
Loaded 71 vehicles from: vehicles/whetstone.txt
Loaded 168 vehicles from: vehicles/bone.txt
Loaded 61 vehicles from: vehicles/flint.txt
Loaded 96 vehicles from: vehicles/tierra.txt
Loaded 96 vehicles from: vehicles/red_county.txt
Total vehicles from files: 1781

---------------------------------------
Running Grand Larceny - by the SA-MP team

---------------------------------------

Number of vehicle models: 173

**Comment by TukangM** [comment]
eh wait

**Comment by developerbcc** [comment]
please link bodyguard.pwn

**Comment by TukangM** [comment]
Abandoned Project
