### ISSUE TITLE
7 errors when compiling citizens.pwn

### ISSUE THREAD

**Issue by Dr-Schnellinger** [ziggi/FCNPC#274]
**I didn't do any modification**

I get:
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(64) : error 017: undefined symbol "FCNPC_MAX_NODES"
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(95) : error 017: undefined symbol "FCNPC_MAX_NODES"
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(107) : error 017: undefined symbol "FCNPC_MOVE_TYPE_WALK"
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(117) : error 017: undefined symbol "speed"
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(117) : warning 215: expression has no effect
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(117) : error 001: expected token: ";", but found ")"
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(117) : error 029: invalid expression, assumed zero
C:\Games\San Andreas Multiplayer\DefaultServer\pawno\citizens.pwn(117) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

**Comment by ziggi** [comment]
Did you changed script somehow? FCNPC.inc should be included

**Comment by Dr-Schnellinger** [comment]
Can you give me a compiled version? Me and my cousin play SA-MP with our two PCs connected via ethernet cable, using the DefaultServer. This server is almost perfect for us but after a while it gets boring. If we had

- NPCs around
- A working score marker for LAN (The score we have is always 0)
- Automatic enter/exit buildings, like on singleplayer

Then the game would be a bit more interesting. I modified some .txt to add a Hydra and a Hunter.

**Comment by ziggi** [comment]
Update FCNPC.inc
Compiled filterscript
[citizens.zip](https://github.com/ziggi/FCNPC/files/12136173/citizens.zip)
