### ISSUE TITLE
Error on local host in windows

### ISSUE THREAD

**Issue by Agfx1376** [ziggi/FCNPC#284]
Skipping legacy plugin 'FCNPC'; It requires memory hacking to run and is therefore broken on open.mp. There should be a replacement component supported by open.mp

**Comment by ziggi** [comment]
Yes, open.mp isn't supported, use sa-mp.

**Comment by Agfx1376** [comment]
No collision data found.
[FCNPC] Warning: Unable to create NPCs. The maxnpc limit in server.cfg is 0.

**Comment by ziggi** [comment]
The maxnpc limit in server.cfg is 0.

**Comment by Agfx1376** [comment]
[https://cdn.discordapp.com/attachments/1084514051540910120/1089231870287429694/image.png](url)

**Comment by Agfx1376** [comment]
[](https://cdn.discordapp.com/attachments/1084514051540910120/1089231870287429694/image.png)

**Comment by Agfx1376** [comment]
[](url)
![Screenshot 2023-03-25 223059](https://user-images.githubusercontent.com/108576964/227731285-ea21bf26-b644-4330-b07c-6318a79df781.png)

**Comment by Agfx1376** [comment]
?

**Comment by Agfx1376** [comment]
@ziggi

**Comment by ziggi** [comment]
![image](https://user-images.githubusercontent.com/1020099/227732789-682c7729-0805-4bf6-bb5c-c49317677b31.png)
?

**Comment by Agfx1376** [comment]
Done
Tnx
