### ISSUE TITLE
FCNPC broke all servers where this plugin is installed!!! Fix It

### ISSUE THREAD

**Issue by TimMRP** [ziggi/FCNPC#286]
HTTP request (ziggi.org/github/lastrelease.php?owner=ziggi&repo=FCNPC&elem=tag_name) began to cause an error when loading servers! Servers cannot start! Fix it

**Comment by ziggi** [comment]
I have problems with my website right now, it will be fixed soon. But you can disable version checks by adding `#define FCNPC_DISABLE_VERSION_CHECK` before `#include <FCNPC>`.
https://github.com/ziggi/FCNPC/wiki/Constants#fcnpc_disable_version_check

**Comment by ziggi** [comment]
Website has been fixed, everything should work fine now.
