### ISSUE TITLE
Pathfinding + climb

### ISSUE THREAD

**Issue by GeDox** [ziggi/FCNPC#29]
Is possible to do this?

http://imgur.com/a/KS1x0

**Comment by ziggi** [comment]
Yes. but it really hard.

**Comment by GeDox** [comment]
Ok, how to detect wall? And how can i climb the wall?

**Comment by ziggi** [comment]
For detecting walls you can use ColAndreas plugin, for climb the wall you can use `FCNPC_SetKeys` with `KEY_JUMP` keys.
But if you ask about it then I think you not be able to implement that.
