### ISSUE TITLE
Can you help fix crash fcnpc 0.3dl , Please help me

### ISSUE THREAD

**Issue by ChubayZ** [ziggi/FCNPC#290]
=========================== FCNPC Exception Handler ============================
Address: 0x7739ff25

Registers:
EAX: 0x24 - EBX: 0x43 - ECX: 0x20 - EDX: 0x33b000
ESI: 0x0 - EDI: 0x750d440 - EBP: 0x19f9dc - ESP: 0x19f9d8

Stack:
0x0: 0x0 - 0x4: 0x19fa18 - 0x8: 0x49f478 - 0xC: 0x20 - 0x10: 0x49face - 0x14: 0x0
0x18: 0x750d440 - 0x1C: 0x0 - 0x20: 0x43

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================

**Comment by ziggi** [comment]
Try to use latest version of the plugin.

**Comment by ChubayZ** [comment]
I tried and it doesn't work, can you help me? Please Help Me ...

**Comment by ziggi** [comment]
You didn't provide any information, so I can't help you.

**Comment by ChubayZ** [comment]
When i run samp-server and login to the game then i exit the game and samp-server automatically disconnects and it shows crash fcncp like this .

=========================== FCNPC Exception Handler ============================
Address: 0x7739ff25

Registers:
EAX: 0x24 - EBX: 0x43 - ECX: 0x20 - EDX: 0x396000
ESI: 0x0 - EDI: 0x74d2440 - EBP: 0x19f9dc - ESP: 0x19f9d8

Stack:
0x0: 0x0 - 0x4: 0x19fa18 - 0x8: 0x49f478 - 0xC: 0x20 - 0x10: 0x49face - 0x14: 0x0
0x18: 0x74d2440 - 0x1C: 0x0 - 0x20: 0x43

Information:
  System: Windows
  SA-MP: 0.3.DL R1
  FCNPC: 2.0.0

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466550
  FUNC_CPlayer__Kill: 0x485020
  FUNC_CPlayer__EnterVehicle: 0x485670
  FUNC_CPlayer__ExitVehicle: 0x485790
  FUNC_CPlayer__SpawnForWorld: 0x487730
  FUNC_GetVehicleModelInfo: 0x4892a0
  FUNC_CConsole__GetIntVariable: 0x490c80
  FUNC_ClientJoin_RPC: 0x497ef0

Pointers:
  VAR_ServerAuthentication: 0x4fc470
  VAR_NetVersion: 0xfde

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5

Callbacks:
  FUNC_CGameMode__OnPlayerGiveDamage: 0x46f050
  FUNC_CGameMode__OnPlayerTakeDamage: 0x46efd0
  FUNC_CGameMode__OnPlayerWeaponShot: 0x46f640
  FUNC_CGameMode__OnPlayerStreamIn: 0x46ebc0
  FUNC_CGameMode__OnPlayerStreamOut: 0x46ec30
  FUNC_CGameMode__OnGameModeExit: 0x46da90
=========================== FCNPC Exception Handler ============================

**Comment by ziggi** [comment]
You have to use latest version of the plugin.
https://github.com/ziggi/FCNPC/releases
