### ISSUE TITLE
Issues when running on Linux

### ISSUE THREAD

**Issue by Ferrec31** [ziggi/FCNPC#293]
Hello, I have a problem, and it is that I am using version 1.8.2 because if I use another version or the most updated one, for some reason the NPCs do not spawn. I have a zombie system, they connect but do not appear. However, when using that version, they do spawn. The problem I have is that when I run this version (1.8.2) on Windows, everything works fine. But when I put it on Linux and the zombies appear, the NPC's death is displayed in the console, and the server freezes, with the CPU at 100%. The player gets frozen or if they try to reconnect, it stays at "connecting to the game" and then displays "server closed." What could this be?
Is there a dependency or something? is a new vps linux (ubuntu)

**Comment by ziggi** [comment]
A lot of crashes was fixed in latest versions of the plugin, so the problem can be in anything.
I think you should find the way how to use latest version. Take a look at breaking changes [here](https://github.com/ziggi/FCNPC/releases/tag/v2.0.0-rc.1) and convert your functions for new version of the plugin.

**Comment by Ferrec31** [comment]
Do you have any idea what the problem is with NPCs connecting but not
appearing? They do appear, but all in the same default position of SA-MP
(x:0, y:0, z:0), but they don't move as they should near a player? However,
using version 1.8.2, they do move as expected.

**Comment by ziggi** [comment]
No, I have no idea. Try to spawn on empty gamemode or try to run something from [example](https://github.com/ziggi/FCNPC/tree/master/sampsvr_files/filterscripts) scripts.
