### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by c0dz3r** [ziggi/FCNPC#313]
Note that NPCs created in the air keep returning to their old position

**Comment by ziggi** [comment]
Yeah, it's not a bug. NPCs does not have their own physics engine.

**Comment by c0dz3r** [comment]
How can I solve?

**Comment by ziggi** [comment]
Change position by yourself with `FCNPC_SetPosition`

**Comment by c0dz3r** [comment]
> Set negative speed and reset to 0 when they hit the ground

How to detect soil?
