### ISSUE TITLE
NPC leaves the server directly after spawning.

### ISSUE THREAD

**Issue by mitarveliki** [ziggi/FCNPC#315]
I am using the latest version of FCNPC. The problem is that the npc spawns and immediately leaves the server. I checked everything and everything is fine. I can't find where the error is. Please help.
![Screenshot 2024-04-19 221539](https://github.com/ziggi/FCNPC/assets/4541365/f8aa3dac-4291-40bb-b99f-0a4568700e42)

**Comment by ziggi** [comment]
You are kicking them, just don't do it.

**Comment by mitarveliki** [comment]
I'm not doing anything, just throw it out. What can cause this error?

**Comment by ziggi** [comment]
Look at the screenshot, you can see (99:2), 99 is an ID and 2 is the reason of disconnect (it means kick or ban).
