### ISSUE TITLE
FCNPC Windows Server Console not closing after rcon exit command

### ISSUE THREAD

**Issue by globrm** [ziggi/FCNPC#319]
Hello Guys.
Currently I have a watchdog that monitors whether the server is running or not and when I do the daily automatic restart of the server by a function in game mode I have noticed that the console does not finish closing when executing the rcon exit command. And therefore the server does not start again.

I tried changing the position and also removing from the plugins parameter in the server.cfg and of course i've already tried to run the server without the watchdog and I can confirm that the console stays on hold until I press the ctrl + c keys.

**Screenshots:**

Here is the plugin running OK
![image](https://github.com/ziggi/FCNPC/assets/173974000/20c93b10-64a0-4e00-acab-fee22e188d7d)

Here is when the gamemode exit command was launched, the other plugins finished successfully
![image](https://github.com/ziggi/FCNPC/assets/173974000/8ec73e93-2467-4dcf-8036-611f4c786574)

Versions:
 - OS: Windows 10 and  Windows Server 2019 Standard
 - SA-MP version: 0.3.7 R2 and 0.3 DL R1 (In samp dl i've been using FCNPC-DL.dl)
 - FCNPC version: FCNPC 2.0.9 

**Thanks you, i really love ur masterpiece plugin.**

**Comment by ziggi** [comment]
Fixed in https://github.com/ziggi/FCNPC/commit/464dd0dbfcfdfeb51a3c80f8a87ecceea304e73c, available in [FCNPC 2.0.10](https://github.com/ziggi/FCNPC/releases)
