### ISSUE TITLE
SKIN DL PROBLEM

### ISSUE THREAD

**Issue by Masaki25** [ziggi/FCNPC#323]
NPCS don't get the skins from the DL version, they are coming as CJ.

**Comment by recepilhanli** [comment]
I have the same problem

**Comment by ziggi** [comment]
> [91be35e](https://github.com/ziggi/FCNPC/commit/91be35e5e87335ad9e61556823b3f2179b4efc37)
> 
> This commit causes the issue

Thanks.

**Comment by ziggi** [comment]
Fixed in 2.0.11
https://github.com/ziggi/FCNPC/releases

**Comment by BVZS** [comment]
![image](https://github.com/user-attachments/assets/487a1318-bebd-420e-8230-387a307d1a85)
I'm using this version and have the same problem
