### ISSUE TITLE
Разворот бота лицом к игроку

### ISSUE THREAD

**Issue by Erlos** [ziggi/FCNPC#34]
Привет, Ziggi. Использую этот плагин для создания ботов-зомби :) Но, вот возникла проблемка. Используя стандартный native FCNPC_SetAngle или FCNPC_AimAtPlayer, для установления бота лицом к игроку, после чего он начинает бить игрока (MeleeAttack), но его всегда разворачивает в любую сторону, но не к игроку. Бывает 1 раз из 10-ти ударит, и то если подловит. В общем, с чем это связано и возможно ли это пофиксить?

**Comment by Erlos** [comment]
В общем-то, изначально я использовал forward ```
FCNPC_OnStreamIn(npcid, forplayerid);
forward FCNPC_OnStreamOut(npcid, forplayerid);
```
Я так понял, OnStreamIn - в поле зрения npc попал playerid, OnStreamOut - playerid вышел из поле зрения npc, так? Ладно, отложу этот вариант и скину тот, который у меня сейчас (взятый с паблика).

http://pastebin.com/4bV0zZ8K

Без массивов, таймеров.

**Comment by ziggi** [comment]
Ты даёшь боту команду - идти в координаты игрока, естественно будут проблемы с углом, так как бот считает, что находится точно там, где находится игрок, а игрок этого не видит, ибо работают коллизии между моделями. Поэтому нужно направлять бота не в точку игрока, а немного до него.

Вот как-то так можно устанавливать правильную позицию:
```Pawn
stock FCNPC_ComeToPlayer(npcid, playerid)
{
	new
		Float:npc_x, Float:npc_y, Float:npc_z,
		Float:npc_angle,
		Float:player_x, Float:player_y, Float:player_z,
		Float:distance,
		Float:result_x, Float:result_y;

	FCNPC_GetPosition(npcid, npc_x, npc_y, npc_z);
	npc_angle = FCNPC_GetAngle(npcid);
	GetPlayerPos(playerid, player_x, player_y, player_z);
	distance = VectorSize(npc_x - player_x, npc_y - player_y, npc_z - player_z);
	GetCoordsInFront(npc_x, npc_y, npc_angle, distance - 0.5, result_x, result_y);

	FCNPC_GoTo(npcid, result_x, result_y, player_z);
}
```

Функция GetCoordsInFront есть в bg.pwn, но продублирую здесь:
```Pawn
stock GetCoordsInFront(Float:x, Float:y, Float:a, Float:distance, &Float:res_x, &Float:res_y)
{
	res_x = x + (distance * floatsin(-a, degrees));
	res_y = y + (distance * floatcos(-a, degrees));
}
```

В целом код очень плох, нет желания в нём копаться, но вот несколько рекомендаций, что я могу дать после беглого осмотра:
- Рекомендую использовать `FCNPC_SetAngleToPlayer(npcid, playerid)`, заместо самописной `FCNPC_Player_Angle(npcid, playerid)`.
- Ещё `FCNPC_OnReachDestination` - это автовызываемая функция плагина, не стоит вызывать её с помощью `CallLocalFunction`.

**Comment by Erlos** [comment]
В общем, доделал свой вариант, немного проблемы с OnStreamIn и OnStreamOut, преследуют игрока до бесконечности, есть ли вариант исправить или необходимо что-то создавать, к примеру IsPlayerInRangeOfPoint?

http://pastebin.com/D7D8erQm

**Comment by ziggi** [comment]
В `FCNPC_OnStreamIn` нужно поставить проверку на запущенность таймера и не запускать ещё один, если он уже работает. А в `FCNPC_OnStreamOut` нужно убивать его (`KillTimer`) если он запущен.

**Comment by Erlos** [comment]
Возник ещё вопрос :) При нанесении урона боту он должен менять цель на атакующего, но не работает через FCNPC_OnTakeDamage, срабатывает при цикле, но тогда цель меняют все боты, а должны только те, кого атаковали. Так же при нанесении урона ботом, урон не отнимается, что делаю не так?

http://pastebin.com/EyfbFPg8

**Comment by ziggi** [comment]
> При нанесении урона боту он должен менять цель на атакующего, но не работает через FCNPC_OnTakeDamage, срабатывает при цикле, но тогда цель меняют все боты, а должны только те, кого атаковали.

Сперва нужно поднять знания в программировании:
```Pawn
public FCNPC_OnTakeDamage(npcid, damagerid, weaponid, bodypart, Float:health_loss)
{
	new npc_index = FCNPC_GetArrayIndex(npcid);
	if (ZombiesInfo[npc_index][IsATarget] == 1) {
		KillTimer(ZombiesInfo[npc_index][Target]);
		ZombiesInfo[npc_index][Target] = SetTimerEx("ZombieOnStreamIn", 1000, true, "ii", ZombiesInfo[npc_index][Connect], damagerid);
		FCNPC_SetAngleToPlayer(ZombiesInfo[npc_index][Connect], damagerid);
		FCNPC_ComeToPlayer(ZombiesInfo[npc_index][Connect], damagerid);
	}
	return true;
}

stock FCNPC_GetArrayIndex(npcid)
{
	for (new i = 0; i < sizeof(ZombiesInfo); i++) {
		if (npcid == ZombiesInfo[i][Connect]) {
			return i;
		}
	}
	return INVALID_PLAYER_ID;
}
```

> Так же при нанесении урона ботом, урон не отнимается, что делаю не так?

Не читаешь инструкцию.

Нужно объявить эти public функции хотя бы в одном из запущенных скриптов:
- OnPlayerGiveDamage
- OnPlayerTakeDamage
- OnPlayerWeaponShot
- OnPlayerStreamIn
- OnPlayerStreamOut

> P.S. Возможно ли отобразить уровень здоровья над голой бота?

Стандартные - нет, можно отобразить с помощью 3D текстов или объектов.

> А также, возможно ли сменить их цвет на радаре?

Да, также как для обычных игроков.

**Comment by Erlos** [comment]
Немного не понял)

> Нужно объявить эти public функции хотя бы в одном из запущенных скриптов:
> 
> OnPlayerGiveDamage
> OnPlayerTakeDamage
> OnPlayerWeaponShot
> OnPlayerStreamIn
> OnPlayerStreamOut

Так чтоль?

```
public OnPlayerGiveDamage(playerid, damagedid, Float:amount, weaponid, bodypart)
{
    FCNPC_OnGiveDamage(npcid, issuerid, weaponid, bodypart, Float:health_loss);
	return true;
}
```

**Comment by ziggi** [comment]
> Так чтоль?

Нет, так:
```Pawn
public OnPlayerGiveDamage(playerid, damagedid, Float:amount, weaponid, bodypart)
{
	return 1;
}
```

**Comment by Erlos** [comment]
Хм.. объявил функцию, но почему-то не работает...

```
public OnPlayerGiveDamage(playerid, damagedid, Float:amount, weaponid, bodypart)
{
	return false;
}

public FCNPC_OnGiveDamage(npcid, issuerid, weaponid, bodypart, Float:health_loss)
{
	new Float: PlayerHP;
	GetPlayerHealth(issuerid, PlayerHP);
	SetPlayerHealth(issuerid, PlayerHP-10.0);
	return true;
}
```

**Comment by ziggi** [comment]
Нужно объявить все.

**Comment by Erlos** [comment]
Объявил все вышеперечисленные функции, везде возвращает false, однако не работает, отнимает от 5-7 хп, вместо заплонированного 10.

**Comment by ziggi** [comment]
Ты чем читаешь вообще? Где я писал, что `OnPlayerWeaponShot` должен возвращать false?
И посмотри чему равны npcid, issuerid - возможно я их местами перепутал.

**Comment by Erlos** [comment]
Дак OnPlayerWeaponShot - true. Скорей перепутал.

```
new Float: PHP;
	GetPlayerHealth(npcid, PHP);
	SetPlayerHealth(npcid, PHP-10.0);
```
Так заработало.

**Comment by ziggi** [comment]
Да, уже поправил. В следующем обновлении будет
