### ISSUE TITLE
FCNPC_ToggleMapAndreasUsage

### ISSUE THREAD

**Issue by karimcambridge** [ziggi/FCNPC#36]
If an FCNPC is about to go under 0.0, turn off map andreas.

If an FCNPC is going higher than 0.0, turn on map andreas.

E.G, Hunter Quarry.

**Comment by Crayder** [comment]
ColAndreas works everywhere, including the "Hunter Quarry"... :P

**Comment by Crayder** [comment]
@karimcambridge regarding https://github.com/ziggi/FCNPC/issues/7#issuecomment-198627561

ColAndreas works everywhere, including the "Hunter Quarry"... :P
