### ISSUE TITLE
Анимации для бота

### ISSUE THREAD

**Issue by Erlos** [ziggi/FCNPC#37]
При создании бота и после его спавна, он должен принимать анимацию, но почему-то ничего не происходит, т.е бот просто стоит.

```
for(new i = 0; i < sizeof(ZombiesInfo); i++)
	{
		ZombiesInfo[i][Connect] = FCNPC_Create(ZombiesInfo[i][Name]);
		PreloadZAnimLib(ZombiesInfo[i][Connect],"CRACK");
 		FCNPC_Spawn(ZombiesInfo[i][Connect], ZombiesInfo[i][Skin], ZombiesInfo[i][SpX], ZombiesInfo[i]           [SpY], ZombiesInfo[i][SpZ]);
        FCNPC_ApplyAnimation(ZombiesInfo[i][Connect], "CRACK", "crckdeth2", 4.1, 0, 1, 1, 1, 1);
	}
```

Как видно пытался сделать подзагрузку анимации, безрезультатно.

`stock PreloadZAnimLib(npcid, animlib[])return FCNPC_ApplyAnimation(npcid, animlib, "null", 0.0, 0, 0, 0, 1, 1);`

**Comment by ziggi** [comment]
FCNPC_ApplyAnimation покажет анимацию только игрокам в зоне стрима.
Предзагрузку нужно делать для игрока, который будет видеть проигрываемую анимацию, а не для бота.
