### ISSUE TITLE
Documentation & precision

### ISSUE THREAD

**Issue by Tyrar** [ziggi/FCNPC#38]
Hi everyone,

I am working with FCNPC for my bot system, nonetheless, I have an issue with bot moving.
When the bot target is higher than the bot, the bot is floating in the air. How can I fixe this bug?

I saw there is a possibility to use MapAndreas, I set the parameters to true, but nothing change.

And the last point: Do you plan to make a dcumentation ?

**Comment by ziggi** [comment]
> I am working with FCNPC for my bot system, nonetheless, I have an issue with bot moving.
When the bot target is higher than the bot, the bot is floating in the air. How can I fixe this bug?

Screenshots?

> I saw there is a possibility to use MapAndreas, I set the parameters to true, but nothing change.

MapAndreas plugin loaded successfully?

> And the last point: Do you plan to make a dcumentation ?

No, I am not interested in this.

**Comment by Tyrar** [comment]
Hum my bad, I didn't see I have to load MapAndreas.

The default plugin should work? http://forum.sa-mp.com/showthread.php?t=120013

Thank you for your answer :)

**Comment by ziggi** [comment]
Use this: http://forum.sa-mp.com/showpost.php?p=3130004&postcount=153

**Comment by Tyrar** [comment]
I try with the plugin, but the problem is still here. SOmetimes, the bot is under the ground, sometimes it is in the air.

On this picture : http://img11.hostingpics.net/pics/440427samp010.png , the bot is nearly in the ground and this one http://img11.hostingpics.net/pics/859550samp007.png the bot is under the ground (it is shooting at me)

**Comment by ziggi** [comment]
Show your code.

**Comment by Tyrar** [comment]
Loading MapAndras:
`MapAndreas_Init(MAP_ANDREAS_MODE_FULL);
    FCNPC_InitMapAndreas(MapAndreas_GetAddress());`

Bot management:
`if (Bot_GetDistanceFromPlayer(npcid, playerid) > 30.0)
        {
            #if DEV_MODE == 1
                printf("NPC(%d) follow Player(%d)", npcid, playerid);
            #endif
                
            if (FCNPC_IsAiming(npcid))
                FCNPC_StopAim(npcid);

            if (!FCNPC_IsMoving(npcid))
                FCNPC_GoToPlayer(npcid, playerid, MOVE_TYPE_AUTO, MOVE_SPEED_AUTO, true);
        }
        else {
            #if DEV_MODE == 1
                printf("NPC(%d) attacks Player(%d)", npcid, playerid);
            #endif

            if (Bot_GetDistanceFromPlayer(npcid, playerid) < 15.0)
                FCNPC_Stop(npcid);

            if (!FCNPC_IsAiming(npcid))
                FCNPC_AimAtPlayer(npcid, playerid, true);
        }`

**Comment by ziggi** [comment]
FCNPC_InitMapAndreas returns 0 or 1?

**Comment by Tyrar** [comment]
It returns 1.

Hum, after recompilation, there is no bug. Just one thing, sometimes, the bot pass trough the bulding to go to the target.
