### ISSUE TITLE
FCNPC_SetAngleToPlayer/FCNPC_SetAngleToPos has issues

### ISSUE THREAD

**Issue by karimcambridge** [ziggi/FCNPC#41]
The calculation your using doesn't always work properly.

**Comment by ziggi** [comment]
I have not seen such, examples are needed.

**Comment by karimcambridge** [comment]
I'll make a video in a couple of hours.

**Comment by NegativeIQ** [comment]
Before i say anything i have modified few things when i tested but nothing that has anything with angles.
In sample body guard script, if you set NPC to follow player his rotation will be offset for 90% (not really sure if its 90 always, it just seems that way). So he will be running sideways toward his next point. But aiming works fine (just to note).

**Comment by ziggi** [comment]
Should be fixed in c42a75206224879f7699bd12d10d8fa1b86114a0.
