### ISSUE TITLE
FCNPC - Debian 8.5

### ISSUE THREAD

**Issue by zsomborlalak8888** [ziggi/FCNPC#42]
#Dear Ziggi!

I have a SaMp serverin Debian 8.5. We need FCNPC for fs, (filterscript) but your's not working, we do not know why. And we started search for this, but we finded only for Ubuntu. Can you help me? We got Debian 8.5 and it is not working.

**Comment by ziggi** [comment]
Compile the plugin by yourself.

**Comment by zsomborlalak8888** [comment]
Hey.

How can I compile the plugin ?:)

**Comment by ziggi** [comment]
Check README.

**Comment by zsomborlalak8888** [comment]
Im not a professional pawner. Can you help me in this? Thats not my gamemode, that's my friends. Can I add you on anythin? Fb, or somethin' where u can help me.

**Comment by ziggi** [comment]
No. Just follow the instruction.

**Comment by zsomborlalak8888** [comment]
But I dont understand this.... Shit... I can follow this? (https://github.com/ziggi/FCNPC/blob/master/README.md)
