### ISSUE TITLE
Compatibility with weapon-config.inc

### ISSUE THREAD

**Issue by rt-2** [ziggi/FCNPC#43]
Hi, it says that we need to declare functions in the script if we want it to work correctly.
Well the function OnPlayerTakeDamage is replaced with weapon-config.inc what should I do then, ignore? I guess not...

Thank you,
rt-2

**Comment by ziggi** [comment]
> Well the function OnPlayerTakeDamage is replaced with weapon-config.inc what should I do then, ignore? I

Yes, it's already defined in weapon-config.
