### ISSUE TITLE
FCNPC_GetAnimation has issue

### ISSUE THREAD

**Issue by diego200052** [ziggi/FCNPC#44]
Hello, I want to obtain the current animation of a NPC created with this plugin, but when I try to get the animation ID with FCNPC_GetAnimation I always get 0 on animationid variable.

Tested with last version of FCNPC on Windows.

Code (OnGamemodeInit):

```
        new npcid;
        new nombre[24];
	for(new i = 0; i < MAX_ZOMBIES; i++)
	{
	    new skinran = random(MAX_ZOMBIES_SKINS);
		format(nombre, 24, "Zombie_%d", i + 1);
		npcid = FCNPC_Create(nombre);
		FCNPC_Spawn(npcid, ZombieSkins[skinran], ZombieSpawns[i][0], ZombieSpawns[i][1], ZombieSpawns[i][2]);
		FCNPC_SetAngle(npcid, ZombieSpawns[0][3]);
		FCNPC_SetInterior(npcid, 0);
                SetTimerEx("TestAnimation", 1000, true, "i", npcid);
	}
```

Code (TestAnimation public function):

```
forward TestAnimation (npcid);
public TestAnimation (npcid)
{
	new animlib[32], animacion[32], animationid, Float:fDelta, loop, lockx, locky, freeze, time;
	FCNPC_GetAnimation(npcid, animationid, fDelta, loop, lockx, locky, freeze, time);
	GetAnimationName(animationid,animlib,32,animacion,32);
	printf("Animlib: %s | Animacion: %s | id: %d | animationid %d", animlib, animacion, npcid, animationid);
	return 1;
}
```

And I get this: (Always, I enter on the server and zombies make a animation but dont show nothing)
```
[13:47:50] Animlib:  | Animacion:  | id: 253 | animationid 0
[13:47:51] Animlib:  | Animacion:  | id: 253 | animationid 0
[13:47:52] Animlib:  | Animacion:  | id: 253 | animationid 0
[13:47:53] Animlib:  | Animacion:  | id: 253 | animationid 0
[13:47:54] Animlib:  | Animacion:  | id: 253 | animationid 0
```
Note: I test with id 253 to avoid flood chat. (A NPC has id 151 - 259; 109 NPC = MAX_ZOMBIES; 259 = MAX_PLAYERS)

When zombie attacks calls this:
`FCNPC_ApplyAnimation(npcid, "ped", "Shove_Partial", 4.1, true, true , true, true, 2900);`

But stills showing in console:
`Animlib:  | Animacion:  | id: 253 | animationid 0`
And the animation "Shove Partial" (in this case) applies correctly to NPC.

PD: FCNPC_GetAnimation returns 1 when calls on TestAnimation

Thanks

**Comment by ziggi** [comment]
[v1.0.1](https://github.com/ziggi/FCNPC/releases/tag/v1.0.1)
- Now we have two different methods of setting animation to NPC:
  - FCNPC_SetAnimation[ByName], FCNPC_ResetAnimation: works with sync
data. Animation is replayed after restreaming. Needs to use
FCNPC_ResetAnimation (with small delay) before replay the current
animation.
  - FCNPC_ApplyAnimation, FCNPC_ClearAnimations: sends RPC packets to
streamed players, works like ApplyAnimation.

This means, that FCNPC_GetAnimation works only with FCNPC_SetAnimation[ByName] functions.
