### ISSUE TITLE
Проблема с работой функции FCNPC_GoTo

### ISSUE THREAD

**Issue by 5LICK** [ziggi/FCNPC#46]
Пробовал воспользоваться функцией `FCNPC_GoTo` но почему-то, после ее использования, NPC просто поворачиваются в каком то направлении и дальше не идут. 
Пробовал потом использовать из примеров скрипт, `FCNPC.pwn`, все так же.. Но вот `FCNPC_GoToPlayer` работает отлично.
Может я что то упустил, но вроде использовал скрипт из примеров, и там код не менял.

**Comment by ziggi** [comment]
Код?

**Comment by 5LICK** [comment]
Помоему вчера в своем коде я написал что то непонятное и он не работал. (Как я и думал, оказывается утром ошибки замечаются лучше)
Сегодня, написал тестовый скрипт все работает хорошо :)
