### ISSUE TITLE
FCNPC Exception - Crash report

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#47]
Just got this report after server restart:

`=========================== FCNPC Exception Handler ============================
Address: 0x6da5f3b8

Registers:
EAX: 0x0 - EBX: 0x1fc9710 - ECX: 0x0 - EDX: 0xf0
ESI: 0x4a - EDI: 0x66cf08 - EBP: 0x769834c8 - ESP: 0x18fe00

Stack:
0x0: 0x1fc9cfc - 0x4: 0x2b00020 - 0x8: 0x6da7448d - 0xC: 0x1fc9c50 - 0x10: 0x469dfb - 0x14: 0x1fc9710
0x18: 0x769810ff - 0x1C: 0x76981136 - 0x20: 0x0

Information:
  System: Windows
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.6.1

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466570
  FUNC_CPlayer__Kill: 0x484620
  FUNC_CPlayer__EnterVehicle: 0x484c70
  FUNC_CPlayer__ExitVehicle: 0x484f50
  FUNC_CPlayer__SpawnForWorld: 0x486d30
  FUNC_GetVehicleModelInfo: 0x488240
  FUNC_CConsole__GetIntVariable: 0x48b5b0
  FUNC_ClientJoin_RPC: 0x4918f0

Pointers:
  VAR_ServerAuthentication: 0x4f5fe8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5
=========================== FCNPC Exception Handler ============================`

**Comment by ziggi** [comment]
This is useless without additional information.
