### ISSUE TITLE
Movement bug

### ISSUE THREAD

**Issue by ziggi** [ziggi/FCNPC#48]
Possible related with #41.

> Hello, I recently realized that my NPC was not setting the angle for the player correctly, because I calculate the angle taking the two positions (NPC and Player). But then I realized that the problem was not in the calculation, but in the position that FCNPC_GetPosition was returning, as in the image below, it is returning the position a little ahead of where I see the NPC (even if the NPC is stopped):
> 
> ![](http://i.imgur.com/7qykKjG.png)
> 
> 
> Studying a little more about this BUG, the same happens after using some function that moves the NPC. The function will always return around 1.0 meters from where npc's SKIN really is.
> 
> NOTE: The same is also true for FCNPC_SetAngleToPlayer. If the player is too close to the NPC, the angle will be reversed, causing the npc to stand with its back to the player.

**Comment by karimcambridge** [comment]
"NOTE: The same is also true for FCNPC_SetAngleToPlayer. If the player is too close to the NPC, the angle will be reversed, causing the npc to stand with its back to the player."

This is EXACTLY my issue.

**Comment by ziggi** [comment]
Confirmed, but I don't know how to fix this yet.

**Comment by NegativeIQ** [comment]
ID_PLAYER_SYNC -> Its never used.  How do we sync NPC's? (Probably we dont, server does it for us...)
Can someone elaborate on these?

Last position (arrival at destination) is not synced to players? (Confirm by forcing update - manually send sync packet for npc?)

**Comment by ziggi** [comment]
Problem in what `SetVelocity(CVector(0.0f, 0.0f, 0.0f));` is calling before NPC has moved to destination. I added a little delay (300ms) for StopMoving, now this seems to be working good.
