### ISSUE TITLE
Error: Function not registered... - FCNPC 1.6.1

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#49]
FCNPC 1.6.1
CentOS
On hostskool.com

**server.cfg**
> crashdetect.so sscanf.so streamer.so mysql.so mysql_static.so whirlpool.so FCNPC.so nativechecker.so

> [01:09:12]    Error: Function not registered: 'FCNPC_AimAtPlayer'
> [01:09:12]    Error: Function not registered: 'FCNPC_Spawn'
> [01:09:12]    Error: Function not registered: 'FCNPC_SetAngleToPlayer'
> [01:09:12]    Error: Function not registered: 'FCNPC_SetVirtualWorld'
> [01:09:12]    Error: Function not registered: 'FCNPC_SetInterior'
> [01:09:12]    Error: Function not registered: 'FCNPC_SetWeapon'
> [01:09:12]    Error: Function not registered: 'FCNPC_SetAmmo'
> [01:09:12]    Error: Function not registered: 'FCNPC_SetFightingStyle'
> [01:09:12]    Error: Function not registered: 'FCNPC_IsInvulnerable'
> [01:09:12]    Error: Function not registered: 'FCNPC_EnterVehicle'
> [01:09:12]    Error: Function not registered: 'FCNPC_ExitVehicle'
> [01:09:12]    Error: Function not registered: 'FCNPC_StopAim'
> [01:09:12]    Error: Function not registered: 'FCNPC_GetWeapon'
> [01:09:12]    Error: Function not registered: 'FCNPC_MeleeAttack'
> [01:09:12]    Error: Function not registered: 'FCNPC_StopAttack'
> [01:09:12]    Error: Function not registered: 'FCNPC_GetVehicleID'
> [01:09:12]    Error: Function not registered: 'FCNPC_GoToPlayer'
> [01:09:12]    Error: Function not registered: 'FCNPC_Create'
> [01:09:12]    Error: Function not registered: 'FCNPC_Destroy'
> [01:09:12]    Error: Function not registered: 'FCNPC_IsValid'

**Comment by ziggi** [comment]
Show me full log. Why you are using two mysql plugins?

**Comment by Yousha** [comment]
Thanks, mysql_static.so removed. (im on hostschool.com)
And here is the logs:

> [11:42:28]  Loading plugin: FCNPC.so
> [11:42:28]   Failed (/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by plugins/FCNPC.so))

and I wanted to load BG FS but failed:

> [11:44:07] RCON (In-Game): Player [Yousha] sent command: loadfs bg
> [11:44:07]    Error: Function not registered: 'FCNPC_AimAtPlayer'
> [11:44:07]    Error: Function not registered: 'FCNPC_Spawn'
> [11:44:07]    Error: Function not registered: 'FCNPC_SetAngleToPlayer'
> [11:44:07]    Error: Function not registered: 'FCNPC_SetVirtualWorld'
> [11:44:07]    Error: Function not registered: 'FCNPC_SetInterior'
> [11:44:07]    Error: Function not registered: 'FCNPC_SetWeapon'
> [11:44:07]    Error: Function not registered: 'FCNPC_SetAmmo'
> [11:44:07]    Error: Function not registered: 'FCNPC_SetFightingStyle'
> [11:44:07]    Error: Function not registered: 'FCNPC_IsInvulnerable'
> [11:44:07]    Error: Function not registered: 'FCNPC_EnterVehicle'
> [11:44:07]    Error: Function not registered: 'FCNPC_ExitVehicle'
> [11:44:07]    Error: Function not registered: 'FCNPC_StopAim'
> [11:44:07]    Error: Function not registered: 'FCNPC_GetWeapon'
> [11:44:07]    Error: Function not registered: 'FCNPC_MeleeAttack'
> [11:44:07]    Error: Function not registered: 'FCNPC_StopAttack'
> [11:44:07]    Error: Function not registered: 'FCNPC_GetVehicleID'
> [11:44:07]    Error: Function not registered: 'FCNPC_GoToPlayer'
> [11:44:07]    Error: Function not registered: 'FCNPC_Create'
> [11:44:07]    Error: Function not registered: 'FCNPC_Destroy'
> [11:44:07]    Error: Function not registered: 'FCNPC_IsValid'
> [11:44:07]   Filterscript 'bg.amx' loaded.

**Comment by ziggi** [comment]
You should build the plugin on your hosting system.

**Comment by Yousha** [comment]
Then I think I should compile it with GCC 4.9 - 32bit right?

**Comment by ziggi** [comment]
You can use any (almost) versions.
