### ISSUE TITLE
Compile problem - The source directory not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by AlexSkyrise** [ziggi/FCNPC#50]
I cant compile this plugin in a Fresh system...

**Error:**
> CMake Error at CMakeLists.txt:49 (add_subdirectory):
>   The source directory /root/FCNPC/lib/subhook does not contain a CMakeLists.txt file.
> -- Configuring incomplete, errors occurred!

**Platform:**
GCC 5.3.0
Slackware 14 64-bit
x64 based system

**Steps:**
cd FCNPC
mkdir build
**cd build**
cmake .. <------ got error here
make

**Comment by ziggi** [comment]
https://github.com/ziggi/FCNPC#how-to-download-all-sources

**Comment by AlexSkyrise** [comment]
Dude, that's what I did...
:: download full source then mkdir build then cd build then cmake ..

**Comment by ziggi** [comment]
> Dude, that's what I did...

No. How you downloaded the sources?

**Comment by AlexSkyrise** [comment]
Oh! sorry, forgot to use --recursive param to get SUBMODULES
