### ISSUE TITLE
MAKE error: gnu/stubs-32.h: No such file or directory

### ISSUE THREAD

**Issue by AlexSkyrise** [ziggi/FCNPC#51]
I tried to MAKE it but got error:

> bash-4.3# make
> [  3%] Building C object lib/subhook/CMakeFiles/subhook.dir/subhook.c.o In file included from /usr/include/features.h:392:0,
>                  from /usr/include/unistd.h:25,
>                  from /root/FCNPC/lib/subhook/subhook_unix.c:27,
>                  from /root/FCNPC/lib/subhook/subhook.c:48:
> /usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
> compilation terminated.
> lib/subhook/CMakeFiles/subhook.dir/build.make:62: recipe for target 'lib/subhook/CMakeFiles/subhook.dir/subhook.c.o' failed
> make[2]: *** [lib/subhook/CMakeFiles/subhook.dir/subhook.c.o] Error 1
> CMakeFiles/Makefile2:470: recipe for target 'lib/subhook/CMakeFiles/subhook.dir/all' failed
> make[1]: *** [lib/subhook/CMakeFiles/subhook.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2

Im using 64-bit OS.

**Comment by ziggi** [comment]
http://lmgtfy.com/?q=gnu%2Fstubs-32.h%3A+No+such+file+or+directory
