### ISSUE TITLE
FCNPC Exception Handler 

### ISSUE THREAD

**Issue by AlexSkyrise** [ziggi/FCNPC#52]
I stopped my server(manually) and got this error in fncp-crash_...txt

> =========================== FCNPC Exception Handler ============================
> Signal 11 (Segmentation fault), address is 2f8e0100 from b73665be
> 
> Backtrace:
>   #0 in plugins/FCNPC.so(_ZN17CExceptionHandler24ExceptionHandlerCallbackEiP9siginfo_tPv+0x116) [0xb60c1656]
>   #1 in linux-gate.so.1(__kernel_rt_sigreturn+0) [0xffffe40c]
>   #2 in plugins/mysql.so(_ZN12CMySQLHandleD1Ev+0x19e) [0xb73665be]
>   #3 in plugins/mysql.so(_ZN12CMySQLHandle7DestroyEv+0x45) [0xb7366885]
>   #4 in plugins/mysql.so(_ZN12CMySQLHandle8ClearAllEv+0x53) [0xb73668f3]
>   #5 in plugins/mysql.so(Unload+0x152) [0xb7380212]
>   #6 in ./samp03svr() [0x80d210b]
>   #7 in ./samp03svr() [0x80aa237]
>   #8 in /lib/libc.so.6(__libc_start_main+0xf3) [0xb74aa7a3]
>   #9 in ./samp03svr() [0x804b4e1]
> 
> Information:
>   System: GNU/Linux
>   SA-MP: 0.3.7 R2-1
>   FCNPC: 1.6.1
> 
> Functions:
>   FUNC_CPlayerPool__DeletePlayer: 0x80d0a90
>   FUNC_CPlayer__Kill: 0x80cb220
>   FUNC_CPlayer__EnterVehicle: 0x80cc1c0
>   FUNC_CPlayer__ExitVehicle: 0x80cc340
>   FUNC_CPlayer__SpawnForWorld: 0x80ccfc0
>   FUNC_GetVehicleModelInfo: 0x80d5d30
>   FUNC_CConsole__GetIntVariable: 0x80a0070
>   FUNC_ClientJoin_RPC: 0x80b0030
> 
> Pointers:
>   VAR_ServerAuthentication: 0x81aa8a8
>   VAR_NetVersion: 0xfd9
> 
> Offsets:
>   OFFSET_RemoteSystemManager: 0x334
>   OFFSET_RemoteSystemSize: 0xc69
>   OFFSET_RemoteSystem__ConnectMode: 0xc62
>   OFFSET_RemoteSystem__Unknown: 0xc67
> =========================== FCNPC Exception Handler ============================

**server_log.txt**

> [00:44:54] Number of vehicle models: 103
> [00:45:26] [debug] Server received interrupt signal
> [00:45:26] [debug] Native backtrace:
> [00:45:26] [debug] #0 b7468180 in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () from plugins/crashdetect.so
> [00:45:26] [debug] #1 b7460064 in _ZN11CrashDetect20PrintNativeBacktraceERSoRKN2os7ContextE () from plugins/crashdetect.so
> [00:45:26] [debug] #2 b7460d64 in _ZN11CrashDetect20PrintNativeBacktraceERKN2os7ContextE () from plugins/crashdetect.so
> [00:45:26] [debug] #3 b7462b9e in _ZN11CrashDetect11OnInterruptERKN2os7ContextE () from plugins/crashdetect.so
> [00:45:26] [debug] #4 b7467465 in ?? () from plugins/crashdetect.so
> [00:45:26] [debug] #5 ffffe40c in __kernel_rt_sigreturn () from linux-gate.so.1
> [00:45:26] [debug] #6 b753a00c in nanosleep () from /lib/libc.so.6
> [00:45:26] [debug] #7 b75703ad in usleep () from /lib/libc.so.6
> [00:45:26] [debug] #8 080aa172 in ?? () from ./samp03svr
> [00:45:26] [debug] #9 b74aa7a3 in __libc_start_main () from /lib/libc.so.6
> [00:45:26] [debug] #10 0804b4e1 in ?? () from ./samp03svr
> [00:45:26] --- Server Shutting Down.

**server.cfg**
plugins crashdetect.so sscanf.so streamer.so mysql.so whirlpool.so FCNPC.so nativechecker.so

ALL plugins are up to date, and using 32-bit OS over x64 system NOW.

**Comment by ziggi** [comment]
Can you give me your server (in zip) to reproduce this?

**Comment by Yousha** [comment]
@AlexSkyrise, check this: https://github.com/ziggi/FCNPC/issues/55#issuecomment-279017969
