### ISSUE TITLE
bg FS - Incorrect parameter count for "FCNPC_GoToPlayer

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#53]
I was testing original **BG** filterscript, and everything works fine except **/bg follow**... it doesnt work and gives error:

> [FCNPC] Error: Incorrect parameter count for "FCNPC_GoToPlayer", 9 != 7

```
if (FCNPC_GetVehicleID(npcid) != INVALID_VEHICLE_ID) {
	radius = 4.0;
	range = radius + 1.0;
	speed = 0.8;
} else {
	radius = 1.0;
	range = radius + 0.5;
	speed = MOVE_SPEED_AUTO;
}

if (!IsPlayerInRangeOfPoint(npcid, range, pos_x, pos_y, pos_z)) {
	FCNPC_GoToPlayer(npcid, playerid, .speed = speed, .radius = radius); // <----------
	KillTimer(gFollowTimer[npcid]);
	gFollowTimer[npcid] = 0;
	return 1;
}
```

**Comment by NegativeIQ** [comment]
Your include version does not match plugin. Just update include and recompile FS. I just now had the same problem :D

**Comment by Yousha** [comment]
But both are same, and used GIT to download/compile them...

**Comment by ziggi** [comment]
You trying to use plugin version from master and include from 1.6.1. Version from master is not tested, please use 1.6.1. Or you should copy new include from `FCNPC/build/pawn/FCNPC.inc`.
