### ISSUE TITLE
Incorrect facing angle

### ISSUE THREAD

**Issue by NegativeIQ** [ziggi/FCNPC#54]
Ok at first i was thinking its just my problem since i tried to modify plugin, but now i compiled clean version from latest master and i still get same problem.

I just tested with simple Body Guard script. When i set NPC to follow me, his facing angle is wrong, its off by ~90 degrees (at least that's what it seems to be.).

**Comment by ziggi** [comment]
Do not use version from master, this version is not tested.

**Comment by NegativeIQ** [comment]
Well someone has to test it... :P Dont worry i know what im getting myself into with unstable code.

Anyway problem is here: https://github.com/ziggi/FCNPC/blob/master/src/CPlayerData.cpp#L1455
I rolled back that to `SetAngle(CMath::RadiansToDegree(atan2(vecFront.fY, vecFront.fX)));` and everything works fine. Also i tried to use fAngle instead of atan2 function but that didnt work.

**Comment by ziggi** [comment]
Should be fixed in c42a75206224879f7699bd12d10d8fa1b86114a0.
