### ISSUE TITLE
Path height difference

### ISSUE THREAD

**Issue by NegativeIQ** [ziggi/FCNPC#56]
How about improving these plugin with a small and simple check for height difference if MapAndreas is used?

Simply when getting Z for next position, check the height difference between current Z and next Z, and if that is bigger than SOME NUMBER, call a callback and wait for return. If return is 1 let NPC continue, and if its 0, stop NPC from moving. Or at least just call that callback and we will be able to stop NPC by ourselves.

EDIT: also a function to set that SOME NUMBER that will be used for height difference check will be useful as someone may want more realistic detection like roleplays and some may want npc zombies being able to jump from a 10meters cliff...

**Comment by ziggi** [comment]
I think it will be useless after pathfinding implementation. Or not?

**Comment by Tyrar** [comment]
Hum it depends, I think it will be usefull until pathfinding implementation will be released !

**Comment by NegativeIQ** [comment]
Well it is meant to compensate for path finding in some way. But than also it wont become useless after.

Lets take pathfinder plugin by pamdex as example and lets take that tolerance is 3 points in heigh (for path finding). That will take some lower buildings and other constructions into account. These callback could be used to apply climbing animation or stop NPC. Well ether way it doesnt cost us anything as its a simple check for info we already have.

**Comment by Tyrar** [comment]
Ok, I tried something. When a NPC walk under a bridge, it is automatically put on the bridge due to the use of MapAndreas.

So, yes, this callback will be useful :)

**Comment by NegativeIQ** [comment]
Well theoretically it can be used for solving bridge problem in combination with some special case code. But the actual goal is to notify scripter of such situation before it happens and allow him/her to make decision. Its just one way to solve problem where NPC's walk over buildings, big rocks and jump from them in less than a second.

**Comment by ziggi** [comment]
Ok, I agreed.

**Comment by ziggi** [comment]
Done.
```Pawn
forward FCNPC_OnChangeZ(playerid, Float:new_z, Float:old_z);
```
