### ISSUE TITLE
Little mistake

### ISSUE THREAD

**Issue by Dayrion** [ziggi/FCNPC#57]
Hey. I was looking for FCNPC_OnGiveDamage. Well, I found it on the presentation : `forward FCNPC_OnGiveDamage(npcid, damagedid, weaponid, bodypart, Float:health_loss);`
Cool, but no. In your include, this is not the same thing : 
`forward FCNPC_OnGiveDamage(npcid, issuerid, weaponid, bodypart, Float:health_loss);`
There is a difference there. Plus, variables made me wrong. 
**npcid** : the player which is hit by the NPC. 
**issuerid** : the NPC's ID
I think you have just to reverse variables.

**Comment by ziggi** [comment]
It was fixed here: https://github.com/ziggi/FCNPC/commit/83f8c412e4f9e72ef71cba55d0c223e2b179bb4c
Will be in the next release.
