### ISSUE TITLE
OnPlayerWeaponShot

### ISSUE THREAD

**Issue by Erlos** [ziggi/FCNPC#62]
Возможно ли изменить урон по боту?
Пытался делать так:

```
public FCNPC_OnTakeDamage(npcid, damagerid, weaponid, bodypart, Float:health_loss)
{
	if(npcid == actor)//new actor; actor = FCNPC_Create(...);
	{
                        if(weaponid == 24) FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-0.40);//DesertEagle
	}
	return 1;
}
```

Однако, все равно отнимает стандартный урон.

**Comment by ziggi** [comment]
FCNPC_OnTakeDamage вообще вызывается? Нужен весь код.

**Comment by Erlos** [comment]
Вот весь код:

http://pastebin.com/emYjFP7Y

> FCNPC_OnTakeDamage вообще вызывается? Нужен весь код.

Ну, исходя из того, что в FCNPC_OnTakeDamage стоит вывод сообщения, и оно выводится. То значит вызывается.

**Comment by ziggi** [comment]
Попробуй добавить `return 0;`.
```Pawn
public FCNPC_OnTakeDamage(npcid, damagerid, weaponid, bodypart, Float:health_loss)
{
    //#pragma unused damagerid
    //#pragma unused health_loss
    if(npcid == actor)
    {
        switch(weaponid)
        {
            case 22: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-0.50);//Colt45
            case 23: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-0.60);//SilencedColt
            case 24: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-2.0);//DesertEagle
            case 25: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-2.50);//PumpShotgun
            case 27: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-3.0);//Spaz12
            case 28,32: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-0.50);//Tec9
            case 29: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-0.60);//MP5
            case 30,31: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-0.50);//M4
            case 34: FCNPC_SetHealth(npcid, FCNPC_GetHealth(npcid)-10.0);//SniperRifle
        }
        new string[67];
        format(string, sizeof(string), "нанесено %.0f урона, у бота %.2f hp", health_loss, FCNPC_GetHealth(npcid));
        SendClientMessageToAll(-1, string);
        return 0;
    }
    return 1;
}
```

**Comment by Erlos** [comment]
Помогло, благодарю.
Ещё, FCNPC крашится при рестарте сервера, не подскажешь, из-за чего?

http://pastebin.com/CYVGn9uq

**Comment by ziggi** [comment]
Не знаю. Код? MySQL используется?

**Comment by Erlos** [comment]
Да, MySQL используется.

**Comment by ziggi** [comment]
Тогда, скорее всего, FCNPC не крашится, а крашится MySQL. Попробуй добавить `mysql_close()` в `OnGameModeExit()`.
Аналогичная проблема: https://github.com/ziggi/FCNPC/issues/55

**Comment by Erlos** [comment]
> Тогда, скорее всего, FCNPC не крашится, а крашится MySQL. Попробуй добавить mysql_close() в OnGameModeExit().
> Аналогичная проблема: #55 

Не помогло, всеравно при вводе 'gmx' в консоль сервера он выключается,

**Comment by ziggi** [comment]
Тогда мне нужен весь список плагинов и весь код.

**Comment by Erlos** [comment]
http://imgur.com/a/FXlw0

Первый - файлы в папке, второе - server.cfg.

**Comment by ziggi** [comment]
Код?

**Comment by Erlos** [comment]
Код всего .pwn мода?

**Comment by ziggi** [comment]
Можно и всего pwn, можно и только тот, что касается FCNPC.

**Comment by Erlos** [comment]
Вот, всё, что связано с FCNPC:

http://pastebin.com/Ja780CDe

**Comment by ziggi** [comment]
Не думаю, что проблема в FCNPC.

**Comment by Erlos** [comment]
http://pastebin.com/30sLN0R4

**Comment by ziggi** [comment]
Попробуй удалить NPC в `OnGameModeExit()` с помощью `FCNPC_Destroy(npcid)`.

**Comment by Erlos** [comment]
Помогло, благодарю.
