### ISSUE TITLE
Freeze NPC

### ISSUE THREAD

**Issue by Erlos** [ziggi/FCNPC#63]
При быстрой стрельбе (зажатой ЛКМ) из скорострельного оружия (М4, АК-47, Тес9 и т.д.) в бота, его фризит и не дает ему возможность стрелять по мне, т.е он просто стоит и целится, и мои хп не отнимаются. Пробовал, передвигать бота ко мне, но даже на ходу эффект тот же (т.е он просто бежит). Возможно ли пофиксить?

P.S. Стреляя из дробовиков, пистолетов, такого не замечал.

**Comment by Erlos** [comment]
Возможно ли пофиксить? Нет?

**Comment by ziggi** [comment]
Пример кода можно?

**Comment by Erlos** [comment]
Кода чего? Когда я в него стреляю, тобишь OnPlayerWeaponShot?

**Comment by ziggi** [comment]
Ты при каждом попадании вызываешь FCNPC_GoToPlayer, что влечёт за собой обновление множества параметров для передвижения. Естественно проблема в этом. Тоже касается и FCNPC_AimAtPlayer.

**Comment by Erlos** [comment]
Хм.. тогда лучше использовать таймер?

**Comment by ziggi** [comment]
Эти функции достаточно вызвать всего один раз и при изменении положения игрока данные в них будут автоматически обновляться.=.

**Comment by Erlos** [comment]
На счет AimAtPlayer, да, работает нормально. А вот в GoToPlayer, получается, когда он достигает меня, то останавливается и стоит и в дальнейшем если я перемещусь, то он и будет стоять.

**Comment by ziggi** [comment]
Так и задумано. Хорошая реализация преследования игрока реализована в
скрипте-примере bg.pwn

**Comment by Erlos** [comment]
Чтоб не создавать новую тему, задам здесь маленький вопросик) При убийстве игрока (от руки бота или другого игрока), бот должен вернуться на точку спавна. Думал в OnPlayerDeath, но бота туда вроде как не вписать. Через FCNPC_OnGiveDamage, бот отправляется на спавн только после того, как убьет игрока (т.е если убьет другой игрок, он будет стоять и стрелять в землю, т.е в меня на расстоянии xD)

**Comment by ziggi** [comment]
Можно и в OnPlayerDeath, но лучше в FCNPC_OnDeath.

**Comment by Erlos** [comment]
Сработает же в том случае если бот убьет игрока. А если игрок1 будет в таргете у бота, и игрока1 убьет игрок2, то бот не вернется на спавн, так же?

**Comment by ziggi** [comment]
Всё зависит от того, как ты напишешь код. Если умрёт игрок - вызовется OnPlayerDeath, если умрёт бот, OnPlayerDeath тоже вызовется. FCNPC_OnDeath вызовется только если умрёт FCNPC бот.
