### ISSUE TITLE
Documentation small error

### ISSUE THREAD

**Issue by rt-2** [ziggi/FCNPC#64]
Hi,
``forward FCNPC_OnGiveDamage(npcid, damagedid, weaponid, bodypart, Float:health_loss);``
should be
``forward FCNPC_OnGiveDamage(npcid, issuerid, weaponid, bodypart, Float:health_loss);``
In the callbacks documentations.

Thank you,
rt-2

**Comment by ziggi** [comment]
Why? Or maybe you mean FCNPC_OnTakeDamage (like [OnPlayerTakeDamage](http://wiki.sa-mp.com/wiki/OnPlayerTakeDamage))?

**Comment by rt-2** [comment]
No, when I used ``FCNPC_OnGiveDamage(npcid, damagedid, weaponid, bodypart, Float:health_loss);`` I got an error that the parameters were wrong, I looked again in the docs, it was supposed to be right, so I searched in the include itself, and I found ``forward FCNPC_OnGiveDamage(npcid, issuerid, weaponid, bodypart, Float:health_loss);``

**Comment by rt-2** [comment]
In your file available in here it says damagerid, but when you open 'FCNPC-1.6.1-windows.zip' from the last release, it says issuerid. I just found that out

**Comment by ziggi** [comment]
It was changed in https://github.com/ziggi/FCNPC/commit/83f8c412e4f9e72ef71cba55d0c223e2b179bb4c and will be in the next release. Because in 1.6.1 issuerid - is actually npcid, and npcid is actually damagedid.

**Comment by rt-2** [comment]
So it's gonna be code breaking?

**Comment by ziggi** [comment]
Yea.

**Comment by rt-2** [comment]
Ok thanks, at least I will get a warning again.
