### ISSUE TITLE
Double damage on NPC since 1.7.0

### ISSUE THREAD

**Issue by rt-2** [ziggi/FCNPC#68]
Hi, I'd like to know more about the modifications to the health system.
I had a completely working script (or I thought), and when I updated to 1.7.0, my zombies had 2 times less health.
I set the health and armor when they spawn, that still works because different level have different health and I can still see that, but they seem to have 1/2 the health of before, or I think probably they get the damage twice.
Anyway I don't know where to start investigating, because I have weapon-config also.
I have a lot of scripts in different gamemodes and filterscripts, so investigating this myself with no information when I made 0 changes on my part will be a nightmare.

This is why I would like to know if you would have any clue or information for me.

Thank you,
rt-2

**Comment by ziggi** [comment]
FCNPC_OnGiveDamage will be fixed In 1.7.0, maybe problem in that?

**Comment by rt-2** [comment]
I tried in the filterscript to return 1 or 0 in that function but it changed nothing.
Do you have a link or more information about it?
I'll try to just disable it or find whatever previous state it was when it was 'broken' and weapon-config should do the rest maybe...
Thank you,
rt-2

**Comment by ziggi** [comment]
Try to add `return 0;` into the FCNPC_OnTakeDamage.

**Comment by rt-2** [comment]
Unfortunately it removed all damages to NPCs.
By the way, it was the OnPlayerGiveDamage and OnPlayerTakeDamage that I played with, not FCNPC_OnGiveDamage.
I don't feel like this new change has something to do with because it shouldn't be called when a player damage an infected, only the other way around, but I can't be sure it's not related

Thank you,
rt-2

**Comment by NegativeIQ** [comment]
1. Did you check OnPlayerGiveDamage for IsPlayerNPC ? (You should)
2. If you want custom damage system, you should return 0; on FCNPC_On Take/Give Damage. Basically what you do that way, is you get notified that player is attacked npc or got attacked by NPC, but you return 0, and it does not take health from npc/player, you do it yourself by setting their health.

**Comment by rt-2** [comment]
My script is more than 3 years old and always worked perfectly without any changes,
All the functions are there, OnPlayerGiveDamage and OnPlayerTakeDamage returns 0, and FCNPC_On Take/Give Damage returns 1.
And now suddenly in the last update, they lose the damage twice.
I am not joking it been working for 3years+ and now suddenly broken by the last update.
It would be very frustrating to try to find this "bug" on my side, without no information of what changed in the last update.

**Comment by rt-2** [comment]
Thank you for the new information, and on my side I found out this:
```
[09/04/2017 09:39:38] INFECTED OnPlayerGiveDamage(playerid:1, damagedid:167, amount:41.250000, weaponid:34, bodypart:9)
[09/04/2017 09:39:38] INFECTED FCNPC_OnTakeDamage(npcid:167, damagerid:1, weaponid:34)
[09/04/2017 09:39:38] INFECTED FCNPC_OnTakeDamage(npcid:167, damagerid:1, weaponid:34)
```
So basicly, weapon-config is not called at all, OnPlayerGiveDamage from inside the filterscript is called once, but then FCNPC_OnTakeDamage gets called twice for a still obscure reason.

Thank you,
rt-2

**Comment by ziggi** [comment]
Probably problem in [this](https://github.com/ziggi/FCNPC/commit/14fcf49982d43d86ceb59cf07a282034ba5b8fc0) commit.
Fix here: 0bbcf9c377316106e6d845b8a4206a083d10ef8c, but it's need to be tested.

**Comment by rt-2** [comment]
Sorry for the delay, but I updated the script to 1.7.1 on my server today and the issue is still there.
``FCNPC_OnTakeDamage`` is still called twice.
Thank you,
rt-2

**Comment by ziggi** [comment]
No, it's tested and everything works right.

**Comment by rt-2** [comment]
You are right, I written a gamemode just to test this and it seems that something since the last update, coupled with something in my script doing that, your include alone does not call ``FCNPC_OnTakeDamage`` twice when alone only. 
Thanks for your help
