### ISSUE TITLE
ColAndreas integration

### ISSUE THREAD

**Issue by ziggi** [ziggi/FCNPC#7]
Integrate ColAndreas.
- http://forum.sa-mp.com/showthread.php?t=586068
- https://github.com/Pottus/ColAndreas

**Comment by NegativeIQ** [comment]
I dont thing removing MapAndreas is smart move. Not everyone is able to sacrifice around 400mb of ram just for NPC's (Speaking about whole SA). I guess smartest way would be to leave MapAndreas.

Also, when you say integrate, just take the easiest way. If its to include whole ColAndreas plugin into FCNPC than so be it, if its exporting base class from ColAndreas and reusing it in FCNPC then its also fine. :D

**Comment by Kar2k** [comment]
or make levels. Load mapandreas or load colandreas.

**Comment by WoutProvost** [comment]
[This thread](http://forum.sa-mp.com/showthread.php?t=598249) shows a system in which ColAndreas (and probably pathfinding) is used instead of MapAndreas. You can try to ask the author if you can have a look at his code.

**Comment by Tyrar** [comment]
Will you plan to integrate colAndreas ?

At this time, I can't help you to implement that, but I can test

**Comment by ziggi** [comment]
@Tyrar, yes, but you can use ColAndreas without integration right now.

**Comment by ziggi** [comment]
Implemented through invoking AMX natives.
