### ISSUE TITLE
Wrong initial clip size with limited ammo

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#71]
When the NPC has say 60 ammo for the colt 45, the NPC performs the following shooting pattern:
1. Shoot 9 bullets + reload
2. Shoot 17 bullets + reload
3. Shoot 17 bullets + reload
4. Shoot 17 bullets

So 9 + 17 + 17 + 17 = 60.
This is not how it works when actual players have 60 ammo for that weapon. They will do 17, 17, 17, 9, which is more logical.

Mentioned in [this thread post](http://forum.sa-mp.com/showpost.php?p=3863602&postcount=3163).

**EDIT:**
The problem is due to the [modulo](https://github.com/ziggi/FCNPC/blob/5174ae967e59ca4c3068161712a6d03e6871e7fb/src/CPlayerData.cpp#L866).

**Comment by WoutProvost** [comment]
Don't have VS installed, so can't test my code, but here's some data on the fix I came up with.

### Fill clip situations
| Ammo | Ammo in clip | Clip size | Result |
| - | - | - | - |
| 60 | 0 | 17 | ammo in clip = 17 |
| 60 | 10 | 17 | nothing, because clip not empty |
| 10 | 0 | 17 | ammo in clip = 10 |
| 10 | 5 | 17 | nothing, because clip not empty |
| 0 | 0 | 17 | nothing, because the next process tick will stop the shooting |

### Reload situations
| Ammo | Ammo in clip | Result |
| - | - | - |
| 60 | 0 | reload |
| 60 | 10 | don't reload, because clip not empty |
| 0 | 0 | don't reload, because no more ammo |

### Set ammo situations
| Old ammo | Ammo in clip | Clip size | New ammo | Result |
| - | - | - | - | - |
| 60 | 0 | 17 | 70 | ammo in clip = 0, handled by next process tick, will be 17 |
| 60 | 10 | 17 | 70 | ammo in clip = 0, handled by next process tick, will be 17 |
| 60 | 0 | 17 | 50 | ammo in clip = 0, handled by next process tick, will be 17 |
| 60 | 10 | 17 | 50 | ammo in clip = 0, handled by next process tick, will be 17 |
| 60 | 0 | 17 | 5 | ammo in clip = 0, handled by next process tick, will be 5 |
| 60 | 10 | 17 | 5 | ammo in clip = 0, handled by next process tick, will be 5 |

**Comment by ziggi** [comment]
Thanks, I think what I know how to fix this.

**Comment by WoutProvost** [comment]
Well, look at [this commit](https://github.com/WoutProvost/FCNPC/commit/08fc660def6ffcee39969c55249a1a980f3a8208), I think this should work, but can't test it.

**Comment by ziggi** [comment]
Yes it is right way, but it will break the reload I guess.

**Comment by ziggi** [comment]
I think it was fixed, need to test.

**Comment by WoutProvost** [comment]
Have looked at your commit, seems to be about the same as my implementation. Can't test just now though, don't have VS available a.t.m.

**Comment by ziggi** [comment]
> Have looked at your commit, seems to be about the same as my implementation.

Yes, but as I say - you has broke the reload.

You set the `m_wAmmoInClip` if `m_wAmmoInClip` is 0.
```C++
if (m_wAmmoInClip == 0) {
	if (m_wAmmo < iClipSize) {
		m_wAmmoInClip = m_wAmmo;
	} else {
		m_wAmmoInClip = iClipSize;
	}
}

Therefore, `bIsNeedToReload` is always be false.
```C++
bool bIsNeedToReload = m_bHasReload
                       && iClipSize > 1
                       && m_wAmmo != 0
                       && m_wAmmoInClip == 0;
```

> Can't test just now though, don't have VS available a.t.m.

I will test this by myself after some time.

**Comment by WoutProvost** [comment]
That would be correct if the decrement happened before the refill block of code. But the decrement happens after that block.

Take the following:
### First process tick:
- m_wAmmoInClip = 1
- don't refill clip, since m_wAmmoInClip is not 0
- decrement m_wAmmoInClip, which becomes 0
- set reload flag to true, since m_wAmmoInClip is 0

### Second process tick:
- execute reload code

### Some process tick that ends the reload:
- set reload flag to false

### First process tick after the reload is done:
- refill clip, since m_wAmmoInClip is 0

**Comment by ziggi** [comment]
Of course, my bad, sorry.
