### ISSUE TITLE
Add pointid parameter in FCNPC_GoByMovePath

### ISSUE THREAD

**Issue by ziggi** [ziggi/FCNPC#79]
```Pawn
native FCNPC_GoByMovePath(npcid, pathid, pointid = 0, type = MOVE_TYPE_AUTO, Float:speed = MOVE_SPEED_AUTO, bool:UseMapAndreas = false, Float:radius = 0.0, bool:setangle = true, Float:dist_offset = 0.0);
```

**Comment by rt-2** [comment]
If added, I think it should be added as ast parameter so nothing will break code, like this:
``native FCNPC_GoByMovePath(npcid, pathid, type = MOVE_TYPE_AUTO, Float:speed = MOVE_SPEED_AUTO, bool:UseMapAndreas = false, Float:radius = 0.0, bool:setangle = true, Float:dist_offset = 0.0, pointid = 0);``

**Comment by ziggi** [comment]
This planned for the next big update (version 2.0), and in this case compatibility doesn't matter. And I want to make more comfortable syntax for functions.

**Comment by ziggi** [comment]
Done.
