### ISSUE TITLE
New feature: get list of current NPCs

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#82]
Just a suggestion: I think it would be great if you make a function to **Get List of Current NPCs**...

**Comment by ziggi** [comment]
For what? Can you show me how you want to use that. I think what `foreach` is enough.

**Comment by NegativeIQ** [comment]
Just loop thru all players and check if they are connected and if they are npc.
Alternatives are foreach, and custom array that would keep track of connected NPC's

There is no need for these inside plugin

**Comment by ziggi** [comment]
> Alternatives are foreach, and custom array that would keep track of connected NPC's

No. Just include foreach before FCNPC and use this:
```Pawn
foreach (new npcid : FCNPC) {
    // npcid - is connected and valid FCNPC
}
```

**Comment by Yousha** [comment]
IK how to get list of NPCs with pawn... Thanks.
But I'm not going to load/include **1200K** lines of code just for a `Foreach`

**Comment by ziggi** [comment]
```Pawn
native FCNPC_GetValidArray(npcs[], const size = sizeof(npcs));
```

**Comment by NegativeIQ** [comment]
In that case i suggest
`native FCNPC_GetValidArray(npcs[], upperbound, const size = sizeof(npcs));`

Upper Bound should give you count number of npc so there is possibility for:

```
new npcArray[MAX_PLAYERS], upperBound = 0;
FCNPC_GetValidArray(npcArray, upperBound);
for(new i = 0 i < upperBound; i++)
{

}

```

**Comment by ziggi** [comment]
I think I will return count number of npc.

**Comment by NegativeIQ** [comment]
That works to

**Comment by ziggi** [comment]
Done.
