### ISSUE TITLE
Version check issue(HTTP)

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#84]
```
** Please update your FCNPC plugin to <html>
<head>
<meta http-equiv="Refresh" content="1; URL=http://www.x.com/dslredirector">
<meta http-equiv="pragma" content="no-cache">
</head>
<body>
Please wait while you are redirected ...
</body>
</html>
 from here: https://github.com/ziggi/FCNPC/releases.
```

Got this output when I was out of Internet Bandwidth, so my ISP redirects ANY request to their Payment Page... so FCNPC couldnt get right data from Github.com (at gamemode start)

**Comment by ziggi** [comment]
I added FCNPC_DISABLE_VERSION_CHECK define now you can define this before include FCNPC and disable version checks.

**Comment by Yousha** [comment]
It's more like you are **ignoring** it than solving it... because most of developers prefer to keep it Enable.

**Comment by ziggi** [comment]
Ok, now this should be better.
