### ISSUE TITLE
FCNPC_Create strlen == 0 no error

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#89]
See [here](https://github.com/ziggi/FCNPC/blob/c36265f65265aa1c114723e90016e4b8779b6f42/src/Natives.cpp#L26) and [here](https://github.com/ziggi/FCNPC/blob/a4e413f6cf4995842cae64f0af270b77458793ba/src/CPlayerManager.cpp#L34). In the first you check for strlen 0 but don't return an error, in the second you don't check for strlen 0 but do return an error. So for some situations the user will get an error and for others he will not and thus don't get any feedback on what he did wrong.

I'd suggest moving the strlen == 0 check to CPlayerManager.cpp so that every case is covered with an explained error.

Already mentioned [here](http://forum.sa-mp.com/showpost.php?p=3892303&postcount=3277) under **EDIT 2**, but you didn't address it.

**Comment by ziggi** [comment]
> Already mentioned here under EDIT 2, but you didn't address it.

Well, I just didn't notice it. Thank you.

**Comment by NegativeIQ** [comment]
Add it [Here](https://github.com/ziggi/FCNPC/blob/c36265f65265aa1c114723e90016e4b8779b6f42/src/CPlayerManager.cpp#L34)

actually add it in both places...

**Comment by WoutProvost** [comment]
What do you mean both places? The position you said is exactly the same as I recommended.

**Comment by NegativeIQ** [comment]
Oh sorry didnt see it. I meant in both palaces as in "native" function and that place.

**Comment by WoutProvost** [comment]
Yeah you could put the error in both places, but that's redundant.
Just moving the check to CPlayerManager.cpp will work as a catch-all.

**Comment by ziggi** [comment]
Should be fixed, thanks for reporting.
