### ISSUE TITLE
Player callbacks hooking in include

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#90]
Attempt to hook the necessary player callbacks, mentioned [here](https://github.com/ziggi/FCNPC/wiki#installation), in the include. This way it doesn't matter if people forget to declare the player callbacks. Not declaring these callbacks can lead to strange behaviour.

**Comment by ziggi** [comment]
Agreed. I don't know why I didn't think of this before.

**Comment by WoutProvost** [comment]
Since the return values of of the SA-MP player functions (except the streaming ones) do different things, we should take this into account. So maybe something like this:

	public OnPlayerTakeDamage(...) {
		new ret = 0;
		#if defined FCNPC_OnPlayerTakeDamage
			ret = FCNPC_OnPlayerTakeDamage(...);
		#endif
		return ret;
	}
	//Remaining hooking code

**Comment by WoutProvost** [comment]
Extra comment as a reminder that the readme and wiki should be updated when this is implemented.

**Comment by NegativeIQ** [comment]
No need to complicate with returning values and adding additional layer...
```
#if !defined FCNPC_OnPlayerTakeDamage
FCNPC_OnPlayerTakeDamage {\
    return 1;\
}
#endif
```

**Comment by ziggi** [comment]
I think what this is done, but I can be wrong.
