### ISSUE TITLE
Server sleep time

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#92]
Apparently, the server's sleep time is not fixed 5 ms. In `server.cfg` you can [change]() this. I don't know if it is possible, but [this](https://github.com/ziggi/FCNPC/blob/4532fdb03941e6c6b9a4f3ca5c40ea10a2632d1f/src/CServer.cpp#L19) should be based on that value.

**Comment by ziggi** [comment]
Thanks, done.
