### ISSUE TITLE
OnVehicleEntryComplete vehicle ID

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#93]
You set the vehicle ID after calling OnVehicleEntryComplete: see [here](https://github.com/ziggi/FCNPC/blob/32e7fe1e0e6dad632c15a3889f7ebfe590dcd7c3/src/CPlayerData.cpp#L805).
However, the naming of the callback implies that everything that should be done is done when the callback is called.

I had something like this:
```Pawn
SomePlayerCallback(playerid, ...) {
	DoSomething(playerid);
}	

OnVehicleEntryComplete(npcid, vehicleid, seat) {
	DoSomething(npcid);
}

DoSomething(playerid) {
	new vehicleid = INVALID_VEHICLE_ID;
	if(FCNPC_IsValid(playerid)) {
		vehicleid = FCNPC_GetVehicleID(playerid); //Will return INVALID_VEHICLE_ID
	} else {
		vehicleid = GetPlayerVehicleID(playerid);
	}
}
```
The solution is of course passing the vehicleid parameter from OnVehicleEntryComplete to DoSomething, but that's not the point here. SetVehicle should be called before OnVehicleEntryComplete.

**Comment by ziggi** [comment]
Agreed, thanks, fixed.
