### ISSUE TITLE
New feature:FCNPC_SetTeam

### ISSUE THREAD

**Issue by kingjan123** [ziggi/FCNPC#94]
Hi , I tried to set fnpc team with SetPlayerTeam but not works,
 I know fcnpc spawns with NO_TEAM but some times we need to set his team for avoid team player attack him such for bodyguard script
Also i tested this code when he take dmage but not completely work when shot with mini gun  ...
```Pawn
	if (!IsPlayerConnected(damagerid)) return 1;
	if (!FCNPC_IsValid(npcid)) return 1;
	if (GetPlayerTeam(npcid) == GetPlayerTeam(damagerid))
	{
		new Float:hp = FCNPC_GetHealth(npcid), Float:armour = FCNPC_GetArmour(npcid);
		hp += health_loss;
		health_loss = 0.0;
		if (hp >= 100.0) {
			health_loss = hp - 100.0;
			hp = 100.0;
		}
		FCNPC_SetHealth(npcid, hp);
		armour += health_loss;
		if (armour >= 100.0) armour = 100;
		FCNPC_SetArmour(npcid, armour);
```

**Comment by ziggi** [comment]
You can `return 0;` in FCNPC_OnTakeDamage to prevent damage.

**Comment by kingjan123** [comment]
I dont want to prevent it for all player i want it just for same team players

**Comment by ziggi** [comment]
You can return 0 only for attackers from the same team, but ok, I will
think about this function.
