### ISSUE TITLE
I created a fcnpc script but when I go ingame it just crashes me out.

### ISSUE THREAD

**Issue by Heroleo911003** [ziggi/FCNPC#95]
FIXED

**Comment by Heroleo911003** [comment]
`=========================== FCNPC Exception Handler ============================
Address: 0x5d39deb0

Registers:
EAX: 0x0 - EBX: 0x3751d4c - ECX: 0x0 - EDX: 0x1
ESI: 0x0 - EDI: 0x0 - EBP: 0x12f344 - ESP: 0x12f330

Stack:
0x0: 0x14d2220 - 0x4: 0x14d2220 - 0x8: 0x0 - 0xC: 0x49b79c0 - 0x10: 0xe0c410a4 - 0x14: 0x37ab954
0x18: 0x4010b6 - 0x1C: 0x14d2220 - 0x20: 0x49b79b4

Information:
  System: Windows
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.7.3

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466570
  FUNC_CPlayer__Kill: 0x484620
  FUNC_CPlayer__EnterVehicle: 0x484c70
  FUNC_CPlayer__ExitVehicle: 0x484f50
  FUNC_CPlayer__SpawnForWorld: 0x486d30
  FUNC_GetVehicleModelInfo: 0x488240
  FUNC_CConsole__GetIntVariable: 0x48b5b0
  FUNC_ClientJoin_RPC: 0x4918f0

Pointers:
  VAR_ServerAuthentication: 0x4f5fe8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5
=========================== FCNPC Exception Handler ============================`

**Comment by ziggi** [comment]
This can be closed?
