### ISSUE TITLE
Weird shooting bug

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#96]
For some reason, an NPC's bullets sometimes go in the wrong direction.
Difficult to explain, here's a [video](https://www.youtube.com/watch?v=7hf1PqGP1xM) in which you'll see exactly what I mean.
NPC accuracy setting is 1.0 and they're aiming at the middle of the clouds.

**Comment by ziggi** [comment]
Can you give me your script for testing this?

**Comment by WoutProvost** [comment]
Sure, I've isolated the part where the bug occurs and it even happens in this testscript. [Click](https://gist.github.com/WoutProvost/406ddbf50ed1f618868669533e67f67f).

**Comment by WoutProvost** [comment]
I suspect it's [this](https://github.com/ziggi/FCNPC/blob/1e969b37a6d1a350aae0d440dc07a2dd5e84f5ed/src/CFunctions.cpp#L203) part of the shooting code.

**Comment by ziggi** [comment]
Done.
