### ISSUE TITLE
Missing Linux Plugin 

### ISSUE THREAD

**Issue by JohnMagdy** [ziggi/FCNPC#99]
Hello everybody, you did good job and it 'd be much better if you uploaded a Linux Plugin (not ubuntu only, which works with all devices [sorry for my bad knowledge about OS])

**Comment by ziggi** [comment]
Not possible. You should build the plugin on your Linux OS by yourself.

**Comment by NegativeIQ** [comment]
Ubuntu covers at least 70-80% of servers, and compiling for the rest of the Unix systems is just insane considering how easy it is to build plugin using instructions without any prior knowledge. Also most of the time plugins compiled on one unix OS will work on another.

**Comment by Yousha** [comment]
@JohnMagdy Im using Slackware and compiled it on 32-bit OS and x64 AMD, you can test it:
[http://zipupload.ir/index.php/download/7K57/1504644995/fcnpc-32bit-slackware14.2.zip.html](http://zipupload.ir/index.php/download/7K57/1504644995/fcnpc-32bit-slackware14.2.zip.html)
